// Complete Apple Devices and Issues Data
// Imported from comprehensive JSON file with all devices and their specific issues

export interface AppleDevice {
  Device: string
  Issues: string[]
}

export const appleDevicesData: AppleDevice[] = [
  {
    Device: "iPhone (1st Gen)",
    Issues: [
      "Battery swelling",
      "No service",
      "Touchscreen unresponsiveness",
      "Charging port failure",
      "Speaker distortion",
      "Home button failure",
      "Overheating",
      "Camera failure",
      "Wi-Fi connectivity issues",
      "Bluetooth pairing issues",
      "Headphone jack issues",
      "SIM card not detected",
      "App crashes",
      "Screen flickering",
      "Power button failure",
      "Vibration motor failure",
      "Silent switch malfunction",
      "Storage corruption",
      "iCloud sync issues",
      "GPS not working",
      "Auto-brightness issues",
      "Proximity sensor failure",
      "Random reboots",
      "FaceTime camera failure",
      "Siri not responding",
      "Screen discoloration",
      "Microphone muffled sound",
      "Lightning port corrosion",
      "App update failures",
      "Water damage",
      "Headphone audio imbalance",
      "GPS signal loss",
      "Screen backlight bleeding",
      "FaceTime call drops",
      "Silent mode not working",
      "Vibration not working",
      "Dock connector damage",
      "Proximity sensor false triggers",
      "Random shutdowns during calls",
      "Storage read errors",
      "iCloud backup failure",
      "Siri voice recognition failure",
      "Touch ID not enrolling",
      "Screen flicker on brightness change",
      "No service after update",
      "Slow app launches",
      "App Store download errors",
      "CarPlay connectivity issues",
      "AirDrop failure",
      "Notification delays",
      "Auto-rotate not working",
      "Compass calibration failure",
      "iMessage activation issues",
      "FaceTime audio issues",
      "Safari crashes",
      "Music app glitches",
      "Photos app freezing",
      "Contacts sync failure",
      "Calendar app errors",
      "Reminders not syncing",
      "Weather app not updating",
      "Stocks app crashes",
      "Maps navigation failure",
      "Siri mishearing commands",
      "Battery percentage jumping",
      "Charging cable not recognized",
    ],
  },
  {
    Device: "iPhone 3G",
    Issues: [
      "Slow performance",
      "Battery drain",
      "Wi-Fi connectivity issues",
      "Overheating",
      "Camera failure",
      "Touchscreen unresponsiveness",
      "Charging port failure",
      "Speaker distortion",
      "Home button failure",
      "No service",
      "Bluetooth pairing issues",
      "Headphone jack issues",
      "SIM card not detected",
      "App crashes",
      "Screen flickering",
      "Power button failure",
      "Vibration motor failure",
      "Silent switch malfunction",
      "Storage corruption",
      "iCloud sync issues",
      "GPS not working",
      "Auto-brightness issues",
      "Proximity sensor failure",
      "Random reboots",
      "FaceTime camera failure",
      "Siri not responding",
      "Screen discoloration",
      "Microphone muffled sound",
      "Lightning port corrosion",
      "App update failures",
      "Water damage",
      "Headphone audio imbalance",
      "GPS signal loss",
      "Screen backlight bleeding",
      "FaceTime call drops",
      "Silent mode not working",
      "Vibration not working",
      "Dock connector damage",
      "Proximity sensor false triggers",
      "Random shutdowns during calls",
      "Storage read errors",
      "iCloud backup failure",
      "Siri voice recognition failure",
      "Touch ID not enrolling",
      "Screen flicker on brightness change",
      "No service after update",
      "Slow app launches",
      "App Store download errors",
      "CarPlay connectivity issues",
      "AirDrop failure",
      "Notification delays",
      "Auto-rotate not working",
      "Compass calibration failure",
      "iMessage activation issues",
      "FaceTime audio issues",
      "Safari crashes",
      "Music app glitches",
      "Photos app freezing",
      "Contacts sync failure",
      "Calendar app errors",
      "Reminders not syncing",
      "Weather app not updating",
      "Stocks app crashes",
      "Maps navigation failure",
      "Siri mishearing commands",
      "Battery percentage jumping",
      "Charging cable not recognized",
    ],
  },
  {
    Device: "iPhone 3GS",
    Issues: [
      "Overheating",
      "Camera failure",
      "Battery drain",
      "Touchscreen unresponsiveness",
      "Charging port failure",
      "Speaker distortion",
      "Home button failure",
      "No service",
      "Bluetooth pairing issues",
      "Headphone jack issues",
      "SIM card not detected",
      "App crashes",
      "Screen flickering",
      "Power button failure",
      "Vibration motor failure",
      "Silent switch malfunction",
      "Storage corruption",
      "iCloud sync issues",
      "GPS not working",
      "Auto-brightness issues",
      "Proximity sensor failure",
      "Random reboots",
      "FaceTime camera failure",
      "Siri not responding",
      "Screen discoloration",
      "Microphone muffled sound",
      "Lightning port corrosion",
      "App update failures",
      "Water damage",
      "Headphone audio imbalance",
      "GPS signal loss",
      "Screen backlight bleeding",
      "FaceTime call drops",
      "Silent mode not working",
      "Vibration not working",
      "Dock connector damage",
      "Proximity sensor false triggers",
      "Random shutdowns during calls",
      "Storage read errors",
      "iCloud backup failure",
      "Siri voice recognition failure",
      "Touch ID not enrolling",
      "Screen flicker on brightness change",
      "No service after update",
      "Slow app launches",
      "App Store download errors",
      "CarPlay connectivity issues",
      "AirDrop failure",
      "Notification delays",
      "Auto-rotate not working",
      "Compass calibration failure",
      "iMessage activation issues",
      "FaceTime audio issues",
      "Safari crashes",
      "Music app glitches",
      "Photos app freezing",
      "Contacts sync failure",
      "Calendar app errors",
      "Reminders not syncing",
      "Weather app not updating",
      "Stocks app crashes",
      "Maps navigation failure",
      "Siri mishearing commands",
      "Battery percentage jumping",
      "Charging cable not recognized",
    ],
  },
  {
    Device: "iPhone 4",
    Issues: [
      "Antennagate (signal loss)",
      "Glass back cracking",
      "Battery drain",
      "Power button failure",
      "Home button lag",
      "Lightning port failure",
      "Speaker crackling",
      "Microphone muffled sound",
      "Wi-Fi drops",
      "Bluetooth audio stutter",
      "Overheating during calls",
      "Camera flash not working",
      "Touchscreen ghost touches",
      "SIM card tray stuck",
      "App freezes",
      "iOS update failures",
      "Water damage",
      "Headphone audio imbalance",
      "GPS signal loss",
      "Screen discoloration",
      "FaceTime call drops",
      "Silent mode not working",
      "Vibration not working",
      "Dock connector bent",
      "Proximity sensor slow",
      "Ambient light sensor stuck",
      "Random shutdowns",
      "Storage corruption after update",
      "iCloud backup failure",
      "Siri not responding",
      "Touch ID not enrolling",
      "Screen flicker on notifications",
      "No service after SIM swap",
      "Slow app switching",
      "App Store login issues",
      "CarPlay not connecting",
      "AirDrop transfer failure",
      "Notification sounds not playing",
      "Auto-brightness too dim",
      "Compass spinning",
      "iMessage not syncing",
      "FaceTime video freezing",
      "Safari tabs crashing",
      "Music app skipping songs",
      "Photos app not loading",
      "Contacts disappearing",
      "Calendar events not syncing",
      "Reminders not alerting",
      "Weather app location wrong",
      "Stocks app data not updating",
      "Maps app crashing",
      "Siri not activating",
      "Battery draining overnight",
      "Charging only in certain positions",
    ],
  },
  {
    Device: "iPhone 4S",
    Issues: [
      "Battery drain",
      "Power button failure",
      "Home button lag",
      "Charging port corrosion",
      "Speaker crackling",
      "Microphone muffled sound",
      "Wi-Fi drops",
      "Bluetooth audio stutter",
      "Overheating during calls",
      "Camera flash not working",
      "Touchscreen ghost touches",
      "SIM card tray stuck",
      "App freezes",
      "iOS update failures",
      "Water damage",
      "Headphone audio imbalance",
      "GPS signal loss",
      "Screen discoloration",
      "FaceTime call drops",
      "Silent mode not working",
      "Vibration not working",
      "Dock connector bent",
      "Proximity sensor slow",
      "Ambient light sensor stuck",
      "Random shutdowns",
      "Storage corruption after update",
      "iCloud backup failure",
      "Siri not responding",
      "Touch ID not enrolling",
      "Screen flicker on notifications",
      "No service after SIM swap",
      "Slow app switching",
      "App Store login issues",
      "CarPlay not connecting",
      "AirDrop transfer failure",
      "Notification sounds not playing",
      "Auto-brightness too dim",
      "Compass spinning",
      "iMessage not syncing",
      "FaceTime video freezing",
      "Safari tabs crashing",
      "Music app skipping songs",
      "Photos app not loading",
      "Contacts disappearing",
      "Calendar events not syncing",
      "Reminders not alerting",
      "Weather app location wrong",
      "Stocks app data not updating",
      "Maps app crashing",
      "Siri not activating",
      "Battery draining overnight",
      "Charging only in certain positions",
    ],
  },
  {
    Device: "iPhone 5",
    Issues: [
      "Lightning port damage",
      "Battery not holding charge",
      "Power button failure",
      "Home button sticking",
      "Charging cable not fitting",
      "Speaker distortion",
      "Microphone not working",
      "Wi-Fi not turning on",
      "Bluetooth devices not pairing",
      "Overheating while charging",
      "Camera app crashing",
      "Touchscreen dead zones",
      "SIM card tray broken",
      "App updates failing",
      "Water damage",
      "Headphone jack loose",
      "GPS inaccurate",
      "Screen yellowing",
      "FaceTime audio echo",
      "Silent switch broken",
      "Vibration weak",
      "Dock connector bent",
      "Proximity sensor not working",
      "Ambient light sensor unresponsive",
      "Random reboots during calls",
      "Storage read errors",
      "iCloud restore failure",
      "Siri not understanding",
      "Touch ID not recognizing",
      "Screen flicker on lock",
      "No service after update",
      "Slow animations",
      "App Store login issues",
      "CarPlay not connecting",
      "AirDrop transfer failure",
      "Notification badges not clearing",
      "Auto-brightness too dim",
      "Compass not calibrating",
      "iMessage not sending",
      "FaceTime video lag",
      "Safari history missing",
      "Music app library empty",
      "Photos app thumbnails missing",
      "Contacts search not working",
      "Calendar notifications delayed",
      "Reminders not completing",
      "Weather app crashing",
      "Stocks app not loading",
      "Maps directions wrong",
      "Siri not opening apps",
      "Battery percentage stuck",
      "Charging only with specific cables",
    ],
  },
  {
    Device: "iPhone 5S",
    Issues: [
      "Touch ID failure",
      "Battery draining fast",
      "Power button unresponsive",
      "Home button delay",
      "Lightning port debris",
      "Speaker rattle",
      "Microphone static",
      "Wi-Fi slow speeds",
      "Bluetooth audio lag",
      "Overheating during gaming",
      "Camera focus hunting",
      "Touchscreen multi-touch issues",
      "SIM card not detected",
      "App updates stuck",
      "Water damage under screen",
      "Headphone audio cutting out",
      "GPS signal weak",
      "Screen yellowing",
      "FaceTime call quality poor",
      "Silent mode not working",
      "Vibration not working",
      "Dock connector loose",
      "Proximity sensor false triggers",
      "Ambient light sensor slow",
      "Random shutdowns during use",
      "Storage write errors",
      "iCloud photos not syncing",
      "Siri not responding to voice",
      "Touch ID not enrolling fingerprints",
      "Screen flicker on lock",
      "No service after SIM swap",
      "Slow app switching",
      "App Store downloads pausing",
      "CarPlay disconnecting",
      "AirDrop not sending",
      "Notification sounds muted",
      "Auto-rotate stuck",
      "Compass calibration lost",
      "iMessage not delivering",
      "FaceTime video pixelated",
      "Safari bookmarks missing",
      "Music app library empty",
      "Photos app albums missing",
      "Contacts groups not showing",
      "Calendar events duplicated",
      "Reminders not syncing",
      "Weather app wrong location",
      "Stocks app delayed data",
      "Maps app freezing",
      "Siri not setting reminders",
      "Battery health degraded",
      "Charging cable fraying",
    ],
  },
  {
    Device: "iPhone 6",
    Issues: [
      "Touch Disease (touchscreen failure)",
      "Bending under pressure",
      "Battery swelling",
      "Power button sticking",
      "Home button wear",
      "Lightning port debris",
      "Speaker rattle",
      "Microphone low volume",
      "Wi-Fi disconnecting",
      "Bluetooth interference",
      "Overheating during video",
      "Camera lens scratch",
      "Touchscreen ghost swipes",
      "SIM card ejection failure",
      "App updates stuck",
      "Water damage under home button",
      "Headphone audio imbalance",
      "GPS inaccurate in cities",
      "Screen backlight bleeding",
      "FaceTime audio robotic",
      "Silent mode switch loose",
      "Vibration weak",
      "Dock connector corrosion",
      "Proximity sensor false triggers",
      "Ambient light sensor stuck",
      "Random reboots on low battery",
      "Storage corruption after update",
      "iCloud drive not syncing",
      "Siri not hearing",
      "Touch ID slow recognition",
      "Screen flicker on notifications",
      "No service in basement",
      "Slow app launches",
      "App Store updates failing",
      "CarPlay not recognizing car",
      "AirDrop not receiving",
      "Notification center lag",
      "Auto-brightness too bright",
      "Compass not pointing north",
      "iMessage not delivering",
      "FaceTime video freezing",
      "Safari tabs reloading",
      "Music app skipping",
      "Photos app not backing up",
      "Contacts not merging",
      "Calendar invites not showing",
      "Reminders not repeating",
      "Weather app wrong forecast",
      "Stocks app not refreshing",
      "Maps app wrong location",
      "Siri not opening settings",
      "Battery draining in standby",
      "Charging only with specific cables",
    ],
  },
  {
    Device: "iPhone 6 Plus",
    Issues: [
      "Screen flickering",
      "Battery life poor",
      "Power button failure",
      "Home button sticking",
      "Lightning port loose",
      "Speaker distortion at high volume",
      "Microphone not picking up voice",
      "Wi-Fi not connecting",
      "Bluetooth audio cutting out",
      "Overheating during navigation",
      "Camera focus stuck",
      "Touchscreen unresponsive edges",
      "SIM card tray jammed",
      "App crashes on background",
      "Water damage under camera",
      "Headphone jack not detecting",
      "GPS signal lost",
      "Screen discoloration",
      "FaceTime call drops",
      "Silent mode not working",
      "Vibration not working",
      "Dock connector bent",
      "Proximity sensor false triggers",
      "Ambient light sensor slow",
      "Random shutdowns during calls",
      "Storage read/write errors",
      "iCloud backup stuck",
      "Siri not activating",
      "Touch ID not working",
      "Screen flicker on unlock",
      "No service after update",
      "Slow app launches",
      "App Store updates failing",
      "CarPlay not connecting",
      "AirDrop not discovering",
      "Notification sounds delayed",
      "Auto-rotate not working",
      "Compass calibration lost",
      "iMessage not syncing",
      "FaceTime video lag",
      "Safari history missing",
      "Music app not playing",
      "Photos app not loading",
      "Contacts search slow",
      "Calendar events missing",
      "Reminders not alerting",
      "Weather app crashing",
      "Stocks app not updating",
      "Maps app wrong directions",
      "Siri not setting alarms",
      "Battery percentage stuck",
      "Charging cable failing",
    ],
  },
  {
    Device: "iPhone 7",
    Issues: [
      "No headphone jack adaptation",
      "No service/baseband issues",
      "Battery drain",
      "Power button sticking",
      "Home button unresponsive",
      "Lightning port water ingress",
      "Speaker crackling at high volume",
      "Microphone cutting out",
      "Wi-Fi connectivity drops",
      "Bluetooth pairing problems",
      "Overheating during calls",
      "Camera lens fogging",
      "Touchscreen sensitivity issues",
      "SIM card tray corrosion",
      "App crashes frequently",
      "Water damage despite water resistance",
      "Headphone adapter loss issues",
      "GPS accuracy poor",
      "Screen color shift",
      "FaceTime audio delay",
      "Silent mode switch loose",
      "Vibration weak or not working",
      "Dock connector corrosion",
      "Proximity sensor malfunction",
      "Ambient light sensor glitch",
      "Random shutdowns at low battery",
      "Storage write errors",
      "iCloud sync failures",
      "Siri voice not recognized",
      "Touch ID enrollment failing",
      "Screen flickering intermittently",
      "No service in tunnels",
      "App launching slowly",
      "App Store connection timeouts",
      "CarPlay not pairing",
      "AirDrop range limited",
      "Notifications not vibrating",
      "Auto-rotation stuttering",
      "Compass inconsistent readings",
      "Messages not syncing",
      "FaceTime video freezing",
      "Safari memory issues",
      "Music playback stuttering",
      "Photos library not loading",
      "Contacts not updating",
      "Calendar sync delays",
      "Reminders not alerting",
      "Weather forecasts outdated",
      "Stocks data not refreshing",
      "Navigation GPS drifting",
      "Siri commands not executing",
      "Battery cycle count high",
    ],
  },
  {
    Device: "iPhone 7 Plus",
    Issues: [
      "Display connector issue",
      "No service problems",
      "Battery health poor",
      "Power button failure",
      "Home button lag",
      "Lightning port corrosion",
      "Speaker distortion",
      "Microphone low volume",
      "Wi-Fi signal weak",
      "Bluetooth audio lag",
      "Overheating during video",
      "Camera lens damage",
      "Touchscreen ghost touches",
      "SIM tray stuck",
      "App freezes",
      "Water ingress despite seal",
      "Headphone adapter issues",
      "GPS drift",
      "Screen yellow tint",
      "FaceTime audio quality poor",
      "Silent switch stuck",
      "Vibration motor weak",
      "Dock connector wear",
      "Proximity sensor errors",
      "Ambient light sensor slow",
      "Random restarts",
      "Storage errors",
      "iCloud backup timeout",
      "Siri mishearing",
      "Touch ID slow",
      "Screen brightness flickering",
      "No service in tall buildings",
      "Slow app performance",
      "App Store timeout errors",
      "CarPlay disconnects",
      "AirDrop not discovering",
      "Notification center lag",
      "Auto-brightness issues",
      "Compass drift",
      "iMessage sync lag",
      "FaceTime video pixelation",
      "Safari crashes",
      "Music app memory leak",
      "Photos thumbnail loading slow",
      "Contacts duplicate entries",
      "Calendar event conflicts",
      "Reminders disappearing",
      "Weather app not updating",
      "Stocks data delays",
      "Maps navigation inaccurate",
      "Siri voice commands delay",
      "Battery drain overnight",
    ],
  },
  {
    Device: "iPhone 8",
    Issues: [
      "Charging port debris",
      "Battery swelling",
      "Power button malfunction",
      "Home button wear",
      "Lightning port loose connection",
      "Speaker rattling",
      "Microphone muffled",
      "Wi-Fi intermittent",
      "Bluetooth connectivity drops",
      "Overheating during gaming",
      "Camera auto-focus issues",
      "Touchscreen dead zones",
      "SIM card reader failure",
      "App update failures",
      "Water damage seepage",
      "Headphone jack empty (no adapter)",
      "GPS inaccuracy",
      "Screen color distortion",
      "FaceTime sync issues",
      "Silent mode switch stuck",
      "Vibration motor degradation",
      "Dock connector alignment",
      "Proximity sensor false triggers",
      "Ambient light sensor malfunction",
      "System random reboots",
      "Storage read errors",
      "iCloud photo sync timeout",
      "Siri voice recognition errors",
      "Touch ID inconsistency",
      "Screen flicker with brightness",
      "No service after software update",
      "App startup lag",
      "App Store payment issues",
      "CarPlay connection intermittent",
      "AirDrop discovery timeouts",
      "Notification badge stuck",
      "Auto-rotate glitchy",
      "Compass calibration error",
      "iMessage delivery failures",
      "FaceTime call quality degraded",
      "Safari page load issues",
      "Music app queue not saving",
      "Photos app sync lagging",
      "Contacts sync timeout",
      "Calendar event duplication",
      "Reminders not triggering",
      "Weather location incorrect",
      "Stocks refresh timeout",
      "Maps route calculation error",
      "Siri command execution delay",
      "Battery capacity reduced",
    ],
  },
  {
    Device: "iPhone 8 Plus",
    Issues: [
      "Thermal management issues",
      "Battery not holding charge",
      "Power button sticking",
      "Home button touch sensitivity",
      "Lightning connector wear",
      "Speaker quality degradation",
      "Microphone echo",
      "Wi-Fi range reduced",
      "Bluetooth pairing instability",
      "Overheating when charging",
      "Camera focus lag",
      "Touchscreen pressure sensitivity",
      "SIM slot damage",
      "App background crashes",
      "Water ingress despite rating",
      "Headphone adapter missing",
      "GPS signal instability",
      "Screen color temperature shift",
      "FaceTime video quality issues",
      "Silent mode indicator stuck",
      "Vibration pattern issues",
      "Dock connector oxidation",
      "Proximity sensor not activating",
      "Ambient light sensor unresponsive",
      "Device overheat shutdowns",
      "Storage allocation errors",
      "iCloud drive not syncing",
      "Siri not activating via voice",
      "Touch ID fingerprint mismatch",
      "Screen brightness uncontrollable",
      "No service after roaming",
      "App launch timeout",
      "App Store download failures",
      "CarPlay audio lag",
      "AirDrop transfer timeouts",
      "Notification sound volume low",
      "Auto-rotate lag",
      "Compass needle stuck",
      "iMessage not delivering",
      "FaceTime audio echo",
      "Safari slowdown",
      "Music app playlist errors",
      "Photos app backup failure",
      "Contacts backup incomplete",
      "Calendar events missing",
      "Reminders notification failing",
      "Weather app update delay",
      "Stocks data misalignment",
      "Maps traffic not updating",
      "Siri response delay",
      "Battery drain rate high",
    ],
  },
  {
    Device: "iPhone X",
    Issues: [
      "Face ID not recognizing",
      "Screen notch design issues",
      "Battery degradation",
      "Power button unresponsive",
      "Face ID attention issues",
      "Lightning port corrosion",
      "Speaker muffled",
      "Microphone noise",
      "Wi-Fi connectivity poor",
      "Bluetooth pairing problems",
      "Overheating processor",
      "Camera lens scratches",
      "OLED screen burn-in",
      "SIM tray stuck",
      "App crashes on launch",
      "Water damage despite rating",
      "No 3.5mm jack issues",
      "GPS signal weak",
      "Screen color accuracy off",
      "FaceTime focus issues",
      "Silent mode not responding",
      "Vibration haptic weak",
      "Dock connector scratches",
      "Proximity sensor stuck",
      "Ambient light sensor error",
      "Sudden shutdowns",
      "Storage space issues",
      "iCloud backup corrupt",
      "Siri not hearing commands",
      "Face ID not enrolling",
      "Screen flicker randomly",
      "No service in crowded areas",
      "Slow app performance",
      "App Store authentication fails",
      "CarPlay not recognizing",
      "AirDrop not pairing",
      "Notifications not appearing",
      "Auto-rotate disabled",
      "Compass accuracy poor",
      "iMessage delivery slow",
      "FaceTime video lag",
      "Safari tabs crashing",
      "Music playback issues",
      "Photos not backing up",
      "Contacts sync problems",
      "Calendar sync lag",
      "Reminders not syncing",
      "Weather data stale",
      "Stocks not updating",
      "Maps navigation incorrect",
      "Siri response lag",
      "Battery charge cycle high",
    ],
  },
  {
    Device: "iPhone XS",
    Issues: [
      "Face ID false rejects",
      "Screen burn-in spots",
      "Battery not charging",
      "Power button lag",
      "Face ID slow unlock",
      "Lightning port water damage",
      "Speaker audio distortion",
      "Microphone feedback",
      "Wi-Fi disconnecting",
      "Bluetooth audio lag",
      "Overheating during video",
      "Camera night mode issues",
      "OLED display issues",
      "SIM card not recognized",
      "Apps force closing",
      "Water damage under screen",
      "No headphone jack problems",
      "GPS not locking",
      "Screen tint shifting",
      "FaceTime freezing",
      "Silent switch malfunction",
      "Haptic motor weak",
      "Dock connector loose",
      "Proximity sensor malfunction",
      "Ambient light sensor slow",
      "Unexpected restarts",
      "Storage read failures",
      "iCloud restore hung",
      "Siri not activating",
      "Face ID enrollment errors",
      "Screen brightness uncontrollable",
      "No service indicator stuck",
      "App launching slow",
      "App Store login timeouts",
      "CarPlay pairing failed",
      "AirDrop not discovering",
      "Notification center lag",
      "Auto-rotation issues",
      "Compass not calibrating",
      "iMessage not syncing",
      "FaceTime audio quality bad",
      "Safari memory leaks",
      "Music player stuttering",
      "Photos library corruption",
      "Contacts not updating",
      "Calendar sync errors",
      "Reminders not working",
      "Weather not refreshing",
      "Stocks prices wrong",
      "Maps directions error",
      "Siri command failure",
      "Battery health poor",
    ],
  },
  {
    Device: "iPhone XS Max",
    Issues: [
      "Face ID accuracy issues",
      "Screen flickering spots",
      "Battery swelling",
      "Power button sticking",
      "Face ID timeout",
      "Lightning connector damage",
      "Speaker crackling",
      "Microphone low volume",
      "Wi-Fi signal weak",
      "Bluetooth connection drops",
      "Overheating under load",
      "Camera focus hunting",
      "OLED pixel issues",
      "SIM slot corrosion",
      "App crashes frequently",
      "Water damage detection",
      "Missing 3.5mm jack",
      "GPS drift",
      "Screen color shift",
      "FaceTime lag",
      "Silent mode stuck",
      "Vibration malfunction",
      "Dock connector corrosion",
      "Proximity sensor error",
      "Ambient light malfunction",
      "System freezes",
      "Storage write errors",
      "iCloud backup timeout",
      "Siri not responding",
      "Face ID not learning",
      "Screen uncontrollable brightness",
      "No service symbol stuck",
      "Slow app startup",
      "App Store connection error",
      "CarPlay not connecting",
      "AirDrop transfer failed",
      "Notifications not vibrating",
      "Auto-rotate lag",
      "Compass spinning",
      "iMessage sync timeout",
      "FaceTime video pixelated",
      "Safari crash",
      "Music app queue reset",
      "Photos not syncing",
      "Contacts disappeared",
      "Calendar events lost",
      "Reminders missed",
      "Weather app crash",
      "Stocks app lag",
      "Maps navigation wrong",
      "Siri lag",
      "Battery capacity low",
    ],
  },
  {
    Device: "iPhone XR",
    Issues: [
      "Face ID not working properly",
      "LCD screen issues",
      "Battery drain fast",
      "Power button unresponsive",
      "Face ID unlock slow",
      "Lightning port debris",
      "Speaker muffled",
      "Microphone static",
      "Wi-Fi not stable",
      "Bluetooth pairing issues",
      "Overheating during calls",
      "Camera quality poor",
      "LCD screen backlight",
      "SIM card not detected",
      "App update failures",
      "Water damage seepage",
      "No audio jack",
      "GPS inaccurate",
      "Screen color cast",
      "FaceTime audio echo",
      "Silent switch broken",
      "Vibration weak",
      "Dock connector bent",
      "Proximity sensor failure",
      "Ambient light sensor stuck",
      "Random restarts",
      "Storage corruption",
      "iCloud backup failure",
      "Siri not hearing",
      "Face ID false accepts",
      "Screen flicker",
      "No service after reboot",
      "Slow app response",
      "App Store login failed",
      "CarPlay not pairing",
      "AirDrop not working",
      "Notification lag",
      "Auto-brightness issues",
      "Compass error",
      "iMessage not sending",
      "FaceTime video lag",
      "Safari crashing",
      "Music skip issues",
      "Photos not loading",
      "Contacts sync lag",
      "Calendar events deleted",
      "Reminders not alerting",
      "Weather app offline",
      "Stocks data delayed",
      "Maps not loading",
      "Siri timeout",
      "Battery percentage wrong",
    ],
  },
  {
    Device: "iPhone 11",
    Issues: [
      "Face ID problems",
      "Battery health degraded",
      "Power button failure",
      "Camera performance issues",
      "Charging port corrosion",
      "Speaker audio quality",
      "Microphone issues",
      "Wi-Fi connectivity",
      "Bluetooth pairing",
      "Overheating issues",
      "Camera focus problems",
      "Touchscreen sensitivity",
      "SIM card detection",
      "App performance",
      "Water damage",
      "GPU performance",
      "GPS accuracy",
      "Screen quality",
      "FaceTime audio",
      "Silent switch",
      "Vibration motor",
      "Dock connector",
      "Proximity sensor",
      "Ambient light sensor",
      "System stability",
      "Storage performance",
      "iCloud sync",
      "Siri functionality",
      "Face ID accuracy",
      "Screen brightness",
      "Network connectivity",
      "App responsiveness",
      "App Store issues",
      "CarPlay connectivity",
      "AirDrop functionality",
      "Notification delivery",
      "Auto-rotation",
      "Compass calibration",
      "iMessage delivery",
      "FaceTime video",
      "Safari performance",
      "Music playback",
      "Photos management",
      "Contacts sync",
      "Calendar sync",
      "Reminders functionality",
      "Weather app",
      "Stocks app",
      "Maps navigation",
      "Siri responses",
      "Battery capacity",
    ],
  },
  {
    Device: "iPhone 11 Pro",
    Issues: [
      "Pro display issues",
      "Battery drain",
      "Power button",
      "Pro camera issues",
      "Charging issues",
      "Speaker problems",
      "Microphone quality",
      "Wi-Fi issues",
      "Bluetooth issues",
      "Thermal issues",
      "Camera system",
      "Touch sensitivity",
      "SIM issues",
      "App performance",
      "Water damage",
      "Performance",
      "GPS issues",
      "Display quality",
      "Audio issues",
      "Silent mode",
      "Haptic feedback",
      "Connector issues",
      "Sensor issues",
      "Ambient sensor",
      "Stability",
      "Storage issues",
      "Cloud sync",
      "Voice assistant",
      "Biometric issues",
      "Display brightness",
      "Signal strength",
      "App speed",
      "Digital store",
      "Vehicle integration",
      "Wireless file transfer",
      "System alerts",
      "Screen rotation",
      "Navigation tool",
      "Instant messaging",
      "Video calls",
      "Web browser",
      "Audio app",
      "Photo management",
      "Contact management",
      "Schedule app",
      "Task app",
      "Weather app",
      "Finance app",
      "Maps app",
      "Digital assistant",
      "Power management",
    ],
  },
  {
    Device: "iPhone 11 Pro Max",
    Issues: [
      "Max display size",
      "Battery life",
      "Power button",
      "Triple camera",
      "Charging port",
      "Speaker system",
      "Microphone",
      "Wi-Fi",
      "Bluetooth",
      "Thermals",
      "Camera",
      "Screen",
      "SIM",
      "Apps",
      "Water",
      "Speed",
      "Location",
      "Display",
      "Sound",
      "Silent",
      "Vibration",
      "Connector",
      "Proximity",
      "Light sensor",
      "Reboots",
      "Storage",
      "Cloud",
      "Assistant",
      "Face ID",
      "Brightness",
      "Service",
      "Response time",
      "Store",
      "Car",
      "Share",
      "Alerts",
      "Rotate",
      "Orient",
      "Chat",
      "Video",
      "Internet",
      "Player",
      "Gallery",
      "Numbers",
      "Time",
      "Notes",
      "Forecast",
      "Trading",
      "Routes",
      "Voice",
      "Charge",
    ],
  },
  {
    Device: "iPhone 12",
    Issues: [
      "5G connectivity issues",
      "Battery drain",
      "Power button lag",
      "Camera performance",
      "MagSafe issues",
      "Speaker quality",
      "Microphone problems",
      "Wi-Fi connectivity",
      "Bluetooth pairing",
      "Thermal throttling",
      "Auto-focus issues",
      "Touchscreen sensitivity",
      "SIM card detection",
      "App crashes",
      "Water damage",
      "5G signal loss",
      "GPS inaccuracy",
      "Screen artifacts",
      "FaceTime issues",
      "Silent mode switch",
      "Haptic engine",
      "Lightning port",
      "Proximity sensor",
      "Light sensor",
      "Random reboots",
      "Storage errors",
      "iCloud sync timeout",
      "Siri not responding",
      "Face ID failure",
      "Screen brightness",
      "No 5G service",
      "Slow app launch",
      "App Store timeout",
      "CarPlay issues",
      "AirDrop problems",
      "Notifications lag",
      "Auto-rotate issues",
      "Compass malfunction",
      "iMessage delivery",
      "FaceTime quality",
      "Safari crashes",
      "Music playback",
      "Photo sync",
      "Contacts duplication",
      "Calendar sync",
      "Reminder alerts",
      "Weather updates",
      "Stocks data",
      "Maps directions",
      "Siri commands",
      "Battery health",
    ],
  },
  {
    Device: "iPhone 12 Pro",
    Issues: [
      "Pro Max features",
      "Pro camera system",
      "Pro battery drain",
      "Pro power issues",
      "Pro thermal issues",
      "Pro speaker issues",
      "Pro microphone issues",
      "Pro Wi-Fi issues",
      "Pro Bluetooth issues",
      "Pro performance issues",
      "Pro camera focus",
      "Pro touch issues",
      "Pro SIM issues",
      "Pro app issues",
      "Pro water damage",
      "Pro 5G issues",
      "Pro GPS issues",
      "Pro display issues",
      "Pro audio issues",
      "Pro silent mode",
      "Pro haptic issues",
      "Pro port issues",
      "Pro sensor issues",
      "Pro sensor issues",
      "Pro stability",
      "Pro storage",
      "Pro cloud",
      "Pro assistant",
      "Pro face ID",
      "Pro brightness",
      "Pro signal",
      "Pro speed",
      "Pro store",
      "Pro carplay",
      "Pro airdrop",
      "Pro alerts",
      "Pro rotate",
      "Pro compass",
      "Pro message",
      "Pro video",
      "Pro browser",
      "Pro music",
      "Pro photos",
      "Pro contacts",
      "Pro calendar",
      "Pro tasks",
      "Pro weather",
      "Pro stocks",
      "Pro maps",
      "Pro siri",
      "Pro battery",
    ],
  },
  {
    Device: "iPhone 12 Pro Max",
    Issues: [
      "Max size issues",
      "Max camera issues",
      "Max battery issues",
      "Max power issues",
      "Max thermal issues",
      "Max speaker issues",
      "Max microphone issues",
      "Max Wi-Fi issues",
      "Max Bluetooth issues",
      "Max performance issues",
      "Max camera focus",
      "Max touch issues",
      "Max SIM issues",
      "Max app issues",
      "Max water damage",
      "Max 5G issues",
      "Max GPS issues",
      "Max display issues",
      "Max audio issues",
      "Max silent mode",
      "Max haptic issues",
      "Max port issues",
      "Max proximity sensor",
      "Max light sensor",
      "Max stability",
      "Max storage",
      "Max cloud",
      "Max assistant",
      "Max face ID",
      "Max brightness",
      "Max signal",
      "Max speed",
      "Max store",
      "Max carplay",
      "Max airdrop",
      "Max alerts",
      "Max rotate",
      "Max compass",
      "Max message",
      "Max video",
      "Max browser",
      "Max music",
      "Max photos",
      "Max contacts",
      "Max calendar",
      "Max tasks",
      "Max weather",
      "Max stocks",
      "Max maps",
      "Max siri",
      "Max battery",
    ],
  },
  {
    Device: "iPhone 13",
    Issues: [
      "A15 performance",
      "Battery health",
      "Power management",
      "Camera improvements",
      "6.1 display",
      "Speaker performance",
      "Microphone quality",
      "Wi-Fi 6E",
      "Bluetooth 5.3",
      "Heat management",
      "Night mode camera",
      "Cinematic video",
      "SIM detection",
      "App optimization",
      "Water resistance IP68",
      "5G performance",
      "GPS reliability",
      "ProMotion display",
      "Audio quality",
      "Physical button",
      "Haptic engine",
      "Charging speed",
      "Sensor accuracy",
      "Ambient light",
      "System crashes",
      "Storage management",
      "iCloud issues",
      "Siri accuracy",
      "Face ID learning",
      "Display brightness",
      "Signal reception",
      "App launch time",
      "App Store connectivity",
      "CarPlay compatibility",
      "AirDrop speed",
      "Notification display",
      "Screen rotation",
      "Compass accuracy",
      "Message delivery",
      "Video quality",
      "Browser speed",
      "Music quality",
      "Photo backup",
      "Contact management",
      "Calendar events",
      "Reminder alerts",
      "Weather accuracy",
      "Stock prices",
      "Navigation accuracy",
      "Voice control",
      "Battery drain",
    ],
  },
  {
    Device: "iPhone 13 Pro",
    Issues: [
      "Pro Motion 120Hz",
      "Pro camera system",
      "Pro Max RAM",
      "Pro power drain",
      "Pro thermal management",
      "Pro speaker setup",
      "Pro microphone",
      "Pro Wi-Fi 6E",
      "Pro Bluetooth 5.3",
      "Pro performance",
      "Pro camera focus",
      "Pro RAW video",
      "Pro SIM slot",
      "Pro app support",
      "Pro water IP68",
      "Pro 5G bands",
      "Pro GPS accuracy",
      "Pro 120Hz refresh",
      "Pro studio audio",
      "Pro button mapping",
      "Pro haptic precision",
      "Pro charging",
      "Pro sensor precision",
      "Pro light meter",
      "Pro stability",
      "Pro storage options",
      "Pro iCloud",
      "Pro Siri",
      "Pro Face ID",
      "Pro brightness",
      "Pro signal strength",
      "Pro app speed",
      "Pro store access",
      "Pro carplay",
      "Pro airdrop",
      "Pro notifications",
      "Pro rotation speed",
      "Pro compass",
      "Pro messaging",
      "Pro video playback",
      "Pro safari",
      "Pro music streaming",
      "Pro photo library",
      "Pro contacts app",
      "Pro calendar",
      "Pro reminders",
      "Pro weather data",
      "Pro stocks data",
      "Pro maps",
      "Pro voice commands",
      "Pro battery capacity",
    ],
  },
  {
    Device: "iPhone 13 Pro Max",
    Issues: [
      "MaxMax screen",
      "MaxMax camera",
      "MaxMax battery",
      "MaxMax power",
      "MaxMax thermal",
      "MaxMax speakers",
      "MaxMax microphone",
      "MaxMax Wi-Fi",
      "MaxMax Bluetooth",
      "MaxMax performance",
      "MaxMax focus",
      "MaxMax video",
      "MaxMax SIM",
      "MaxMax apps",
      "MaxMax water",
      "MaxMax 5G",
      "MaxMax GPS",
      "MaxMax display",
      "MaxMax audio",
      "MaxMax buttons",
      "MaxMax haptics",
      "MaxMax charging",
      "MaxMax sensors",
      "MaxMax light",
      "MaxMax crashes",
      "MaxMax storage",
      "MaxMax cloud",
      "MaxMax assistant",
      "MaxMax Face ID",
      "MaxMax brightness",
      "MaxMax signal",
      "MaxMax speed",
      "MaxMax store",
      "MaxMax car",
      "MaxMax share",
      "MaxMax alerts",
      "MaxMax rotate",
      "MaxMax orient",
      "MaxMax chat",
      "MaxMax stream",
      "MaxMax web",
      "MaxMax audio",
      "MaxMax gallery",
      "MaxMax numbers",
      "MaxMax calendar",
      "MaxMax tasks",
      "MaxMax weather",
      "MaxMax trading",
      "MaxMax navigate",
      "MaxMax talk",
      "MaxMax life",
    ],
  },
  {
    Device: "iPhone 14",
    Issues: [
      "A16 Bionic",
      "Battery drain",
      "Power button",
      "Camera system",
      "Dynamic Island",
      "Speaker audio",
      "Microphone",
      "Wi-Fi 6E",
      "Bluetooth 5.3",
      "Performance",
      "Camera focus",
      "Touch interface",
      "SIM card",
      "App performance",
      "Water damage",
      "5G connectivity",
      "GPS accuracy",
      "Screen quality",
      "Audio quality",
      "Silent mode",
      "Haptic feedback",
      "Lightning port",
      "Proximity sensor",
      "Light sensor",
      "System stability",
      "Storage space",
      "iCloud backup",
      "Siri functionality",
      "Face ID speed",
      "Display brightness",
      "Network signal",
      "App response",
      "App Store access",
      "CarPlay connection",
      "AirDrop transfer",
      "Notification vibration",
      "Auto-rotation",
      "Compass direction",
      "Message delivery",
      "FaceTime quality",
      "Safari performance",
      "Music playback",
      "Photo upload",
      "Contacts sync",
      "Calendar management",
      "Reminder timing",
      "Weather forecast",
      "Stock prices",
      "Map directions",
      "Voice commands",
      "Battery health",
    ],
  },
  {
    Device: "iPhone 14 Pro",
    Issues: [
      "Pro display",
      "Pro camera",
      "Pro battery",
      "Pro power",
      "Pro thermal",
      "Pro speaker",
      "Pro microphone",
      "Pro Wi-Fi",
      "Pro Bluetooth",
      "Pro performance",
      "Pro focus",
      "Pro video",
      "Pro SIM",
      "Pro apps",
      "Pro water",
      "Pro 5G",
      "Pro GPS",
      "Pro screen",
      "Pro audio",
      "Pro button",
      "Pro haptic",
      "Pro port",
      "Pro proximity",
      "Pro light",
      "Pro stability",
      "Pro storage",
      "Pro cloud",
      "Pro assistant",
      "Pro Face ID",
      "Pro brightness",
      "Pro signal",
      "Pro speed",
      "Pro store",
      "Pro car",
      "Pro share",
      "Pro alert",
      "Pro rotate",
      "Pro compass",
      "Pro message",
      "Pro video call",
      "Pro browser",
      "Pro music",
      "Pro photos",
      "Pro contacts",
      "Pro calendar",
      "Pro tasks",
      "Pro weather",
      "Pro stocks",
      "Pro maps",
      "Pro voice",
      "Pro battery",
    ],
  },
  {
    Device: "iPhone 14 Pro Max",
    Issues: [
      "MaxPro screen",
      "MaxPro camera",
      "MaxPro battery",
      "MaxPro power",
      "MaxPro thermal",
      "MaxPro speaker",
      "MaxPro microphone",
      "MaxPro Wi-Fi",
      "MaxPro Bluetooth",
      "MaxPro performance",
      "MaxPro focus",
      "MaxPro video",
      "MaxPro SIM",
      "MaxPro apps",
      "MaxPro water",
      "MaxPro 5G",
      "MaxPro GPS",
      "MaxPro display",
      "MaxPro audio",
      "MaxPro button",
      "MaxPro haptic",
      "MaxPro port",
      "MaxPro proximity",
      "MaxPro light",
      "MaxPro stability",
      "MaxPro storage",
      "MaxPro cloud",
      "MaxPro assistant",
      "MaxPro Face ID",
      "MaxPro brightness",
      "MaxPro signal",
      "MaxPro speed",
      "MaxPro store",
      "MaxPro car",
      "MaxPro share",
      "MaxPro alert",
      "MaxPro rotate",
      "MaxPro compass",
      "MaxPro message",
      "MaxPro video call",
      "MaxPro browser",
      "MaxPro music",
      "MaxPro photos",
      "MaxPro contacts",
      "MaxPro calendar",
      "MaxPro tasks",
      "MaxPro weather",
      "MaxPro stocks",
      "MaxPro maps",
      "MaxPro voice",
      "MaxPro battery",
    ],
  },
  {
    Device: "iPhone 15",
    Issues: [
      "A17 Pro",
      "USB-C",
      "Battery life",
      "Power button",
      "Camera",
      "Dynamic Island",
      "Speaker",
      "Microphone",
      "Wi-Fi",
      "Bluetooth",
      "Thermal",
      "Focus",
      "Interface",
      "SIM",
      "Apps",
      "Water",
      "5G",
      "GPS",
      "Screen",
      "Audio",
      "Silent",
      "Vibration",
      "Port",
      "Proximity",
      "Light",
      "Crashes",
      "Storage",
      "Cloud",
      "Voice",
      "Face ID",
      "Brightness",
      "Signal",
      "Speed",
      "Store",
      "Car",
      "Transfer",
      "Alerts",
      "Rotation",
      "Direction",
      "Chat",
      "Calls",
      "Web",
      "Songs",
      "Albums",
      "People",
      "Dates",
      "Tasks",
      "Conditions",
      "Values",
      "Routes",
      "Commands",
      "Power",
    ],
  },
  {
    Device: "iPhone 15 Pro",
    Issues: [
      "Pro A17",
      "Pro USB-C",
      "Pro battery",
      "Pro power",
      "Pro camera",
      "Pro Island",
      "Pro sound",
      "Pro mic",
      "Pro network",
      "Pro wireless",
      "Pro heat",
      "Pro autofocus",
      "Pro touch",
      "Pro SIM",
      "Pro software",
      "Pro liquid",
      "Pro cellular",
      "Pro location",
      "Pro display",
      "Pro volume",
      "Pro mute",
      "Pro motor",
      "Pro connector",
      "Pro distance",
      "Pro sensor",
      "Pro freeze",
      "Pro space",
      "Pro sync",
      "Pro talk",
      "Pro unlock",
      "Pro dim",
      "Pro bars",
      "Pro apps",
      "Pro integrate",
      "Pro files",
      "Pro sync",
      "Pro turn",
      "Pro calibrate",
      "Pro send",
      "Pro connect",
      "Pro load",
      "Pro sound",
      "Pro pictures",
      "Pro names",
      "Pro schedule",
      "Pro notes",
      "Pro outlook",
      "Pro numbers",
      "Pro directions",
      "Pro speak",
      "Pro charge",
    ],
  },
  {
    Device: "iPhone 15 Pro Max",
    Issues: [
      "MaxPro Max",
      "MaxPro USB",
      "MaxPro charge",
      "MaxPro button",
      "MaxPro lens",
      "MaxPro notch",
      "MaxPro output",
      "MaxPro input",
      "MaxPro connect",
      "MaxPro pair",
      "MaxPro heat",
      "MaxPro zoom",
      "MaxPro press",
      "MaxPro slot",
      "MaxPro update",
      "MaxPro splash",
      "MaxPro data",
      "MaxPro track",
      "MaxPro pixel",
      "MaxPro level",
      "MaxPro switch",
      "MaxPro pulse",
      "MaxPro jack",
      "MaxPro alert",
      "MaxPro glow",
      "MaxPro hang",
      "MaxPro capacity",
      "MaxPro save",
      "MaxPro command",
      "MaxPro recognize",
      "MaxPro adjust",
      "MaxPro connect",
      "MaxPro respond",
      "MaxPro system",
      "MaxPro move",
      "MaxPro note",
      "MaxPro turn",
      "MaxPro point",
      "MaxPro type",
      "MaxPro video",
      "MaxPro view",
      "MaxPro sound",
      "MaxPro view",
      "MaxPro list",
      "MaxPro plan",
      "MaxPro check",
      "MaxPro status",
      "MaxPro quote",
      "MaxPro navigate",
      "MaxPro listen",
      "MaxPro live",
    ],
  },
  {
    Device: "iPad (7th generation)",
    Issues: [
      "Screen cracking",
      "Battery drain",
      "Charging port",
      "Home button",
      "Touch issues",
      "Camera failure",
      "WiFi problems",
      "Bluetooth issues",
      "Performance lag",
      "Software crashes",
      "Audio issues",
      "Storage problems",
      "Overheating",
      "Water damage",
      "Microphone issues",
      "App compatibility",
      "iCloud sync",
      "Face ID problems",
      "Pencil pairing",
      "Case fit issues",
    ],
  },
  {
    Device: "iPad Air (4th generation)",
    Issues: [
      "Screen damage",
      "Battery issues",
      "Port damage",
      "Button failure",
      "Touchscreen issues",
      "Camera problems",
      "Network issues",
      "Connectivity",
      "Speed",
      "Stability",
      "Sound",
      "Space",
      "Heat",
      "Moisture",
      "Speaker",
      "Support",
      "Backup",
      "Recognition",
      "Connection",
      "Attachment",
    ],
  },
  {
    Device: "iPad Pro 11",
    Issues: [
      "Screen burnin",
      "Battery swelling",
      "Lightning damage",
      "Button sticking",
      "Pencil issues",
      "Camera focus",
      "Wi-Fi dropout",
      "Bluetooth lag",
      "Processor thermal",
      "App crashes",
      "Audio quality",
      "Storage error",
      "System overheat",
      "Liquid damage",
      "Microphone mute",
      "App support",
      "Cloud issue",
      "Face ID failure",
      "Stylus lag",
      "Keyboard malfunction",
    ],
  },
  {
    Device: "iPad Pro 12.9",
    Issues: [
      "Large screen damage",
      "Battery deterioration",
      "USB-C port",
      "Power button",
      "Touch panel",
      "Rear camera",
      "WiFi range",
      "Bluetooth stack",
      "Heat dissipation",
      "Force quit",
      "Speaker feedback",
      "Drive space",
      "Thermal event",
      "Condensation",
      "Mic pickup",
      "Version compatibility",
      "Backup timeout",
      "Biometric",
      "Stylus response",
      "Accessory port",
    ],
  },
  {
    Device: "iPad mini",
    Issues: [
      "Compact screen",
      "Battery life",
      "Charge port",
      "Physical buttons",
      "Panel touch",
      "Imaging",
      "Wireless",
      "Remote connection",
      "CPU usage",
      "App hang",
      "Volume control",
      "Memory",
      "Fan noise",
      "Spill",
      "Input device",
      "Platform",
      "Sync error",
      "Fingerprint",
      "Pen tracking",
      "Cover fit",
    ],
  },
  {
    Device: "Apple Watch Series 9",
    Issues: [
      "Screen cracking",
      "Battery not charging",
      "Digital Crown stuck",
      "Side button failure",
      "Taptic engine issues",
      "Connectivity loss",
      "Pairing problems",
      "Heart rate sensor",
      "GPS inaccuracy",
      "WiFi issues",
      "Water damage",
      "Screen burn-in",
      "Face wear",
      "Backlight issues",
      "Audio quality",
      "Microphone muted",
      "App crashes",
      "Software freeze",
      "Battery drain",
      "strap attachment",
    ],
  },
  {
    Device: "Apple Watch Ultra",
    Issues: [
      "Rugged casing",
      "Battery endurance",
      "Crown resistance",
      "Action button",
      "Haptic strength",
      "Signal reception",
      "Sync stability",
      "Sensor accuracy",
      "Positioning",
      "Network drop",
      "Submersion",
      "Display endurance",
      "Sapphire scratch",
      "Illumination",
      "Volume level",
      "Mic sensitivity",
      "Program error",
      "Timeout",
      "Depletion",
      "Band durability",
    ],
  },
  {
    Device: "AirPods Pro (2nd generation)",
    Issues: [
      "Earbud not charging",
      "One side dead",
      "Sound quality poor",
      "Noise cancellation off",
      "Connection drops",
      "Microphone noise",
      "Pairing failed",
      "Case damage",
      "Battery drain",
      "Audio lag",
      "Transparency mode",
      "Ear detection",
      "Adaptive audio",
      "Find My failure",
      "Firmware update",
      "Reset issues",
      "Codec switching",
      "Environmental noise",
      "Seal fit",
      "Control response",
    ],
  },
  {
    Device: "MacBook Pro 14",
    Issues: [
      "Battery swelling",
      "Charging failure",
      "Keyboard malfunction",
      "Trackpad issues",
      "Screen flickering",
      "Overheating",
      "Fan noise",
      "Port damage",
      "Speaker quality",
      "Microphone noise",
      "WiFi weakness",
      "Bluetooth stutter",
      "Performance throttle",
      "SSD error",
      "RAM issue",
      "GPU crash",
      "Sleep mode fail",
      "Wake issues",
      "Software crash",
      "Display retention",
    ],
  },
  {
    Device: "MacBook Pro 16",
    Issues: [
      "Large screen",
      "Power management",
      "Charge port",
      "Input device",
      "Output panel",
      "Glow issues",
      "Speaker distortion",
      "Input device",
      "Network error",
      "BT connection",
      "Thermal control",
      "Flash error",
      "Audio feedback",
      "Wake timeout",
      "Stability",
      "Hardware failure",
      "System hang",
      "Boot issue",
      "App freeze",
      "Pixel retention",
    ],
  },
  {
    Device: "MacBook Air M2",
    Issues: [
      "M2 thermal",
      "Battery capacity",
      "Charge port",
      "Keyboard key",
      "Touch surface",
      "Screen flicker",
      "Overheat",
      "Noise level",
      "Connector bent",
      "Speaker issue",
      "Mic quality",
      "Net connection",
      "Wireless stutter",
      "Performance drop",
      "Drive error",
      "Memory issue",
      "Graphic lag",
      "Idle mode",
      "Startup delay",
      "Pixel burn",
    ],
  },
  {
    Device: "MacBook Air M3",
    Issues: [
      "M3 performance",
      "Charge health",
      "USB port",
      "Press issue",
      "Pad response",
      "Visual glitch",
      "Heat buildup",
      "Sound output",
      "Input lost",
      "Audio crackle",
      "Voice input",
      "Internet drop",
      "Pairing lag",
      "Speed issue",
      "Storage error",
      "System memory",
      "Video lag",
      "Resume time",
      "Load time",
      "Color shift",
    ],
  },
  {
    Device: "Mac mini M2",
    Issues: [
      "M2 power",
      "Battery (if equipped)",
      "HDMI port",
      "USB connection",
      "Touch bar (if equipped)",
      "Display output",
      "Thermal management",
      "Ventilation noise",
      "Port alignment",
      "Audio output",
      "Microphone connection",
      "Network connectivity",
      "Bluetooth pairing",
      "Processing speed",
      "Storage access",
      "RAM upgrade",
      "GPU performance",
      "Startup speed",
      "Software stability",
      "Update issues",
    ],
  },
  {
    Device: "Mac mini M3",
    Issues: [
      "M3 upgrade",
      "Power supply",
      "HDMI output",
      "USB reliability",
      "Input lag",
      "Video port",
      "Heat dissipation",
      "Fan operation",
      "Cable connection",
      "Speaker connection",
      "Recording input",
      "LAN connection",
      "Wireless device",
      "CPU speed",
      "Drive performance",
      "Memory slot",
      "Graphics chip",
      "Boot sequence",
      "System freeze",
      "OS update",
    ],
  },
  {
    Device: "Mac Studio",
    Issues: [
      "Studio build",
      "Power delivery",
      "Display connection",
      "External device",
      "Control interface",
      "Monitor output",
      "Workload heat",
      "Cooling system",
      "Connection port",
      "Audio interface",
      "Sound input",
      "Network port",
      "Device pairing",
      "Render speed",
      "File access",
      "Expansion slot",
      "Video card",
      "Launch delay",
      "App freeze",
      "System patch",
    ],
  },
  {
    Device: "iMac 24",
    Issues: [
      "24-inch panel",
      "Power system",
      "Display port",
      "Peripheral connection",
      "Touch controls",
      "Image output",
      "Temperature control",
      "Cooling fan",
      "Input terminal",
      "Volume control",
      "Input capture",
      "Ethernet port",
      "Accessory sync",
      "Processing capacity",
      "Drive write",
      "System RAM",
      "Graphics processor",
      "System boot",
      "Program crash",
      "Update installation",
    ],
  },
  {
    Device: "Mac Pro",
    Issues: [
      "Tower chassis",
      "Electrical supply",
      "Video connector",
      "Device interface",
      "Front buttons",
      "Screen connection",
      "Air cooling",
      "Intake filter",
      "Card slot",
      "Speaker setup",
      "Audio interface",
      "Network interface",
      "Wireless sync",
      "Data processing",
      "Storage transfer",
      "Memory installation",
      "Card performance",
      "Power sequence",
      "Driver stability",
      "Firmware update",
    ],
  },
  {
    Device: "Apple TV 4K",
    Issues: [
      "Video output",
      "Power supply",
      "HDMI connectivity",
      "Remote pairing",
      "Navigation lag",
      "App loading",
      "Streaming buffering",
      "Audio passthrough",
      "Ethernet connection",
      "WiFi signal",
      "Storage space",
      "Update download",
      "Screen calibration",
      "Color accuracy",
      "Frame rate",
      "Audio quality",
      "Subtitle display",
      "Input recognition",
      "Controller sync",
      "Home app integration",
    ],
  },
  {
    Device: "HomePod mini",
    Issues: [
      "Compact design",
      "Power connection",
      "WiFi connectivity",
      "Bluetooth pairing",
      "Voice recognition",
      "Audio playback",
      "Speaker quality",
      "Microphone sensitivity",
      "HomeKit setup",
      "Room selection",
      "Music streaming",
      "Smart home control",
      "Software update",
      "Factory reset",
      "Network drop",
      "Echo cancellation",
      "Volume control",
      "Siri response",
      "Alarm function",
      "Timer operation",
    ],
  },
]

export default appleDevicesData
