// Ghana Locations Data - All regions, cities, and towns
export const GHANA_LOCATIONS = {
  "Greater Accra": {
    region: "Greater Accra",
    cities: [
      "Accra",
      "Accra Central",
      "Accra New Town",
      "Accra North",
      "Accra West",
      "Adabraka",
      "Alajo",
      "Asylum Down",
      "Cantonments",
      "Circle",
      "Christian Village",
      "Jamestown",
      "Korle Gonno",
      "Korle Bu",
      "Korle Wokon",
      "Makola",
      "North Ridge",
      "Osu",
      "Osu Anorhor",
      "Osu Badu",
      "Osu Klottey",
      "Osu Oxford Street",
      "Osu RE",
      "Ridge",
      "Ring Road Central",
      "Victoriaborg",
      "West Ridge",
      "Kinbu",
      "Kukuruduku",
      "Kwame Nkrumah Circle",
      "Mamobi",
      "Ministries",
      "Nima",
      "Nima Maamobi",
      "North Kaneshie",
      "South Odorkor",
      "South Ridge",
      "Tudor",
      "Abelemkpe",
      "Dzorwulu",
      "East Legon",
      "East Legon Hills",
      "Kanda",
      "Kanda Estates",
      "Kanda Highway",
      "Labone",
      "Roman Ridge",
      "Tesano",
      "Tema",
      "Tema Community 1",
      "Tema Community 2",
      "Tema Community 3",
      "Tema Community 4",
      "Tema Community 5",
      "Tema Community 6",
      "Tema Community 7",
      "Tema Community 8",
      "Tema Community 9",
      "Tema Community 10",
      "Tema Community 11",
      "Tema Community 12",
      "Tema Community 13",
      "Tema East",
      "Tema Harbour",
      "Tema Industrial Area",
      "Tema New Town",
      "Ashaiman",
      "Batsona",
      "Lebene",
      "Lolonya",
      "Adenta",
      "Agbogba",
      "Ashaley Botwe",
      "Ashongman",
      "Atomic",
      "Ayi Mensah",
      "Dome",
      "East Legon Hills",
      "Frafraha",
      "Haatso",
      "Kwabenya",
      "Lartebiokoshie",
      "Legon",
      "Madina",
      "Oyarifa",
      "Pantang",
      "Spintex",
      "Trassaco Valley",
      "Abokobi",
      "La",
      "Labadi",
      "Labadi Estates",
      "Larteh",
      "Mallam",
      "Nungua",
      "Teshie",
      "Teshie Camp",
      "Teshie First Junction",
      "Teshie Nungua",
      "Bortianor",
      "Gbawe",
      "Kokrobite",
      "Kotoku",
      "Larteh",
      "Mamprobi",
      "Mataheko",
      "Mpoase",
      "New Achimota",
      "Odorkor",
      "Santa Maria",
      "Tantra Hill",
      "Tebibiano",
      "Weija",
      "Weija Barrier",
      "Weija Gbawe",
      "Weija Junction",
      "Weija Lido",
      "Weija New Town",
      "Weija Old Town",
      "Weija Syvan",
      "Weija Town",
      "Zenu",
      "Zenu Lido",
      "Zenu Syvan",
      "Zenu Town",
      "Zoti",
      "Zoti Junction",
      "Sege",
      "Sege Junction",
      "Ada",
      "Ada Foah",
      "Ada Kasseh",
      "Ada New Town",
      "Ada Old Town",
      "Ada Songor",
      "Ada Tsakpo",
      "Ada Whasaman",
      "Adafoah",
      "Adaime",
      "Adjei Kojo",
      "Agbogloshie",
      "Amanfrom",
      "Amasaman",
      "Aplaku",
      "Ashalaja",
      "Budumburam",
      "Budumburam Camp",
      "Doryumu",
      "Gbegbeyise",
      "Gbetsile",
      "Gomoa Budumburam",
      "Gomoa Fete",
      "Gomoa Fetteh",
      "Gomoa Ojobi",
      "Gomoa Otuam",
      "Gomoa Pomadze",
      "Kpong",
      "Kpongunor",
      "Larteh Akuapim",
      "Prampram",
      "Prampram Junction",
      "Saki",
      "Sakumono Village",
      "Ningo",
      "Ningo-Prampram",
      "Old Ningo",
      "New Ningo",
      "Dodowa",
      "Doryumu",
      "Oyarifa",
      "Asutsuare",
      "Akuse",
    ],
  },
  Ashanti: {
    region: "Ashanti",
    cities: [
      "Kumasi",
      "Adum",
      "Ahmadiyya",
      "Ahinsan",
      "Ahodwo",
      "Amanfrom",
      "Anloga",
      "Antoa",
      "Asafo",
      "Asawase",
      "Asokwa",
      "Asuoyeboah",
      "Atasomanso",
      "Atonsu",
      "Ayigya",
      "Bantama",
      "Bohyen",
      "Buokrom",
      "Danyame",
      "Dichemso",
      "Ejisu",
      "Fante New Town",
      "Kaase",
      "Krofrom",
      "Kwadaso",
      "Kwamo",
      "Moshie Zongo",
      "Nhyiaeso",
      "Oforikrom",
      "Ohwimase",
      "Patasi",
      "Pankrono",
      "Race Course",
      "Roman Hill",
      "Santase",
      "Sofoline",
      "Subin",
      "Suame",
      "Tafo",
      "Tafokwaboah",
      "Tanoso",
      "Tarkwa Maakro",
      "Theophilus",
      "Tucson",
      "Zongo",
      "Fomena",
      "New Edubiase",
      "Obogu",
      "Poano",
      "Agogo",
      "Akyease",
      "Asiwa",
      "Asokore",
      "Juansa",
      "Konongo",
      "Konongo-Odumase",
      "Nkwantakese",
      "Nyinahin",
      "Bekwai",
      "Mampong",
      "Obuasi",
      "Offinso",
      "Manso Amenfi",
      "Manso Atwereboana",
      "Jacobu",
      "Adubiaso",
      "Akropong",
      "Akwapem",
      "Asuogya",
      "Bareese",
      "Beposo",
      "Buoyem",
      "Domeabra",
      "Kuntanse",
      "Kwabre",
      "Aduman",
      "Akrofuom",
      "Ahenema Kokoben",
      "Boamang",
      "Bremang",
      "Fufuo",
      "Krobo",
      "Mamponteng",
      "Nkwantakese",
      "Adugyama",
      "Ahwerewa",
      "Asuogya",
      "Bareese",
      "Beposo",
      "Buoyem",
      "Domeabra",
      "Mankranso",
      "Pokuase",
      "ACP",
      "New Town",
      "Santeo",
      "Tantra Hill",
      "Amasaman",
      "Amenfi",
      "Anyaa",
      "Sowutuom",
      "Bubiashie",
      "Doblo",
      "Mayera",
      "Obom",
      "Ofankor",
      "Barrier",
      "Pantang",
      "Zongo",
      "Ada",
      "Songor",
      "Adafoah",
      "Adaime",
      "Tsakpo",
      "Whasaman",
      "Agbogloshie",
      "Amanfrom",
      "Aplaku",
      "Ashalaja",
      "Budumburam",
      "Camp",
      "Doryumu",
      "Gbegbeyise",
      "Gbetsile",
      "Junction",
      "Gomoa Dawurampong",
      "Gomoa Lome",
      "Gomoa Mankoadze",
      "Gomoa Nyanyano",
      "Gomoa Ota",
      "Gomoa Potsin",
      "Gomoa Wawase",
      "Kpong",
      "Larteh Akuapim",
      "Mallam",
      "Atta",
      "Mamfe",
      "Mankoadze",
      "Nsawam",
      "Adoagyiri",
      "Oyarifa",
      "Pantang",
      "Prampram",
      "Saki",
      "Sakumono Village",
      "Bosome Freho",
      "Aboabo",
      "Ahinsan",
      "Ahodwo",
      "Amanfrom",
      "Anloga",
      "Antoa",
      "Asafo",
      "Asokwa",
      "Asuoyeboah",
      "Atasomanso",
      "Atonsu",
      "Ayigya",
      "Bantama",
      "Bohyen",
      "Buokrom",
      "Danyame",
      "Dichemso",
      "Ejisu",
      "Fante New Town",
      "Kaase",
      "Krofrom",
      "Kwadaso",
      "Kwamo",
      "Moshie Zongo",
      "Nhyiaeso",
      "Oforikrom",
      "Ohwimase",
      "Patasi",
      "Pankrono",
      "Race Course",
      "Roman Hill",
      "Santase",
      "Sofoline",
      "Subin",
      "Suame",
      "Tafo",
      "Tafokwaboah",
      "Tanoso",
      "Tarkwa Maakro",
      "Theophilus",
      "Tucson",
      "Zongo",
      "Adansi North",
      "Akimfo",
      "Akrokerri",
      "Ayaase",
      "Bomoa",
      "Dompoase",
      "Fomena",
      "New Edubiase",
      "Obogu",
      "Poano",
      "Adansi South",
      "Afigya Kwabre North",
      "Boamang",
      "Bremang",
      "Domeabra",
      "Fufuo",
      "Krobo",
      "Mamponteng",
      "Afigya Kwabre South",
      "Ahafo Ano North",
      "Adugyama",
      "Ahwerewa",
      "Akwapem",
      "Asuogya",
      "Bareese",
      "Beposo",
      "Buoyem",
      "Domeabra",
      "Mankranso",
      "Ahafo Ano South East",
      "Ahafo Ano South West",
      "Akrofuom District",
      "Ada",
      "Adubiaso",
      "Adugyama",
      "Ahwerewa",
      "Akropong",
      "Akwapem",
      "Asuogya",
      "Bareese",
      "Beposo",
      "Buoyem",
      "Domeabra",
      "Jacobu",
      "Manso Amenfi",
      "Manso Atwereboana",
      "Amansie South",
      "Amansie West",
      "Asante Akim Central",
      "Agogo",
      "Akyease",
      "Asiwa",
      "Asokore",
      "Domeabra",
      "Juansa",
      "Konongo",
      "Konongo-Odumase",
      "Nkwantakese",
      "Nyinahin",
      "Asante Akim North",
      "Asante Akim South",
      "Aduman",
      "Agogo",
      "Akyease",
      "Asiwa",
      "Asokore",
      "Domeabra",
      "Juansa",
      "Konongo",
      "Konongo-Odumase",
      "Nkwantakese",
      "Nyinahin",
      "Atwima Kwanwoma",
      "Atwima Mponua",
      "Atwima Nwabiagya",
      "Atwima Nwabiagya North",
      "Bosome Freho",
      "Ejisu",
      "Ejura/Sekyedumase",
      "Ejura",
      "Sekyedumase",
      "Juaben",
      "Kwabre East",
      "Mampong",
      "Obuasi",
      "Obuasi East",
      "Offinso",
      "Offinso North",
      "Sekyere Afram Plains",
      "Sekyere Central",
      "Sekyere East",
      "Sekyere Kumawu",
      "Sekyere South",
      "Suame",
      "Tafo",
      "Asokore Mampong",
      "Old Tafo",
      "Oforikrom",
      "Asokwa",
      "Subin",
      "Kwadaso",
      "Nhyiaeso",
      "Manhyia",
      "Bantama",
      "Obuasi",
      "Offinso",
      "Sekyere South",
    ],
  },
  Western: {
    region: "Western",
    cities: [
      "Sekondi",
      "Takoradi",
      "Airport Ridge",
      "Anaji",
      "Apowa",
      "Beach Road",
      "Bogoso Road",
      "Diabene",
      "Effiakuma",
      "Essikadu",
      "Fijai",
      "Kansaworodo",
      "Kojokrom",
      "Kwesimintsim",
      "Market Circle",
      "Nkroful",
      "Ntankoful",
      "Tanokrom",
      "Whindo",
      "Agona Nkwanta",
      "Akwidaa",
      "Apemenyimhen",
      "Asanta",
      "Asemda",
      "Asempa",
      "Asempanaye",
      "Atwea",
      "Beposo",
      "Bokro",
      "Busua",
      "Dixcove",
      "Evalue Ajomoro Gwira",
      "Evalue Gwira",
      "Mangyea",
      "Mpatado",
      "Ngyiresia",
      "Prestea",
      "Prestea-Huni Valley",
      "Savuma",
      "Shama",
      "Tikobo No. 1",
      "Tikobo No. 2",
      "Tikobo No. 3",
      "Amenfi Central",
      "Amenfi East",
      "Amenfi West",
      "Bia",
      "Bibiani",
      "Anhwiaso",
      "Bekwai",
      "Chirano",
      "Sefwi Akontombra",
      "Sefwi Anhwiaso",
      "Sefwi Bekwai",
      "Sefwi Wiawso",
      "Sefwi Asafokrom",
      "Sefwi Chirano",
      "Sefwi Debiso",
      "Sefwi Wiaso",
      "Bodi",
      "Ellembelle",
      "Aiyinase",
      "Ankasa",
      "Nkroful",
      "Nkroful Junction",
      "Nkroful New Town",
      "Nkroful Old Town",
      "Nkroful Zongo",
      "Jomoro",
      "Aiyinase",
      "Ankasa",
      "Asempanaye",
      "Beposo",
      "Bokro",
      "Busua",
      "Dixcove",
      "Evalue Ajomoro Gwira",
      "Evalue Gwira",
      "Half Assini",
      "Mangyea",
      "Mpatado",
      "Ngyiresia",
      "Nkroful",
      "Savuma",
      "Tikobo No. 1",
      "Mpohor",
      "Mpohor/Wassa East",
      "Nzema East",
      "Aiyinase",
      "Ankasa",
      "Asempanaye",
      "Prestea-Huni Valley",
      "Prestea",
      "Huni Valley",
      "Sefwi Akontombra",
      "Adabokrom",
      "Asempanaye",
      "Beposo",
      "Bokro",
      "Busua",
      "Dixcove",
      "Evalue Ajomoro Gwira",
      "Evalue Gwira",
      "Mangyea",
      "Mpatado",
      "Ngyiresia",
      "Savuma",
      "Tikobo No. 1",
      "Sefwi Wiawso",
      "Adabokrom",
      "Asempanaye",
      "Beposo",
      "Bokro",
      "Busua",
      "Dixcove",
      "Evalue Ajomoro Gwira",
      "Evalue Gwira",
      "Mangyea",
      "Mpatado",
      "Ngyiresia",
      "Savuma",
      "Tikobo No. 1",
      "Tikobo No. 2",
      "Shama",
      "Abuesi",
      "Aboadze",
      "Adjoa",
      "Anaji",
      "Apowa",
      "Bogoso",
      "Daboase",
      "Effasu",
      "Effiakuma",
      "Essikado",
      "Essikadu",
      "Inchaban",
      "Kojokrom",
      "Kwesimintsim",
      "Mpintsin",
      "Nsuta",
      "Shama Junction",
      "Tarkwa",
      "Tarkwa-Nsuaem",
      "Tarkwa-Nsuaem Municipal",
      "Aboso",
      "Akyempim",
      "Amenfi",
      "Anwomaso",
      "Apinto",
      "Asempanaye",
      "Banso",
      "Beposo",
      "Bokro",
      "Bonsa",
      "Daboase",
      "Damang",
      "Dompim",
      "Dompim-Pepesa",
      "Huni Valley",
      "Iduapriem",
      "Kwabeng",
      "Manso Amenfi",
      "Mpatado",
      "Nsuta",
      "Prestea",
      "Samahu",
      "Tarkwa",
      "Teberebie",
      "Tebrempong",
      "Wassa Amenfi Central",
      "Wassa Amenfi East",
      "Wassa Amenfi West",
      "Asempanaye",
      "Beposo",
      "Bokro",
      "Busua",
      "Dixcove",
      "Evalue Ajomoro Gwira",
      "Evalue Gwira",
      "Mangyea",
      "Mpatado",
      "Ngyiresia",
      "Savuma",
      "Tikobo No. 1",
      "Tikobo No. 2",
      "Wassa East",
      "Aiyinase",
      "Ankasa",
      "Asempanaye",
      "Beposo",
      "Bokro",
      "Busua",
      "Dixcove",
      "Evalue Ajomoro Gwira",
      "Evalue Gwira",
      "Mangyea",
      "Mpatado",
      "Ngyiresia",
      "Nkroful",
      "Savuma",
      "Axim",
      "Bonsaso",
      "Daboase",
      "Damang",
      "Effasu",
      "Essaman",
      "Essamang",
      "Heman",
      "Huni Valley",
      "Kwamekrom",
      "Mpohor",
      "Nsuta",
      "Prestea",
      "Sefwi Akontombra",
      "Sefwi Anhwiaso",
      "Sefwi Bekwai",
      "Sefwi Wiawso",
      "Teleku Bokazo",
      "Wassa Akropong",
      "Wassa Amenfi",
    ],
  },
  Central: {
    region: "Central",
    cities: [
      "Cape Coast",
      "Abura",
      "Abeadze Dominase",
      "Abeadze Kyiakor",
      "Abura Dunkwa",
      "Abutiakwa",
      "Akwidaa",
      "Anafo",
      "Ankaful",
      "Anomabo",
      "Apam",
      "Bakaano",
      "Bakaano Junction",
      "Bakaano New Town",
      "Bakaano Old Town",
      "Bakaano Zongo",
      "Bakaano-Abeadze",
      "Bakaano-Kotokuraba",
      "Bakaano-Ola",
      "Bakaano-Takoradi Road",
      "Bakaano-Wesleyan",
      "Bakaano-Yamfo",
      "Abakrampa",
      "Abakrampa Junction",
      "Abakrampa New Town",
      "Abakrampa Old Town",
      "Abakrampa Zongo",
      "Abakrampa-Asebu",
      "Abakrampa-Kwamankese",
      "Abura",
      "Asebu",
      "Kwamankese",
      "Moree",
      "Narkwa",
      "Narkwa Junction",
      "Narkwa New Town",
      "Narkwa Old Town",
      "Narkwa Zongo",
      "Agona Abodom",
      "Agona Abodom Junction",
      "Agona Abodom New Town",
      "Agona Abodom Old Town",
      "Agona Abodom Zongo",
      "Agona Nyakrom",
      "Agona Nyakrom Junction",
      "Agona Nyakrom New Town",
      "Agona Nyakrom Old Town",
      "Agona Nyakrom Zongo",
      "Agona Swedru",
      "Agona Swedru Junction",
      "Agona Swedru New Town",
      "Agona Swedru Old Town",
      "Agona Swedru Zongo",
      "Bobikuma",
      "Bobikuma Junction",
      "Bobikuma New Town",
      "Bobikuma Old Town",
      "Bobikuma Zongo",
      "Kotokuam",
      "Kotokuam Junction",
      "Kotokuam New Town",
      "Kotokuam Old Town",
      "Kotokuam Zongo",
      "Mankrong Junction",
      "Mankrong New Town",
      "Mankrong Old Town",
      "Mankrong Zongo",
      "Nkranfwi",
      "Nkranfwi Junction",
      "Nkranfwi New Town",
      "Nkranfwi Old Town",
      "Nkranfwi Zongo",
      "Nkum",
      "Nkum Junction",
      "Nkum New Town",
      "Nkum Old Town",
      "Nkum Zongo",
      "Nyakrom",
      "Nyakrom Junction",
      "Nyakrom New Town",
      "Nyakrom Old Town",
      "Nyakrom Zongo",
      "Agona West Municipal",
      "Ajumako",
      "Ajumako Junction",
      "Ajumako New Town",
      "Ajumako Old Town",
      "Ajumako Zongo",
      "Enyan Abaasa",
      "Enyan Abaasa Junction",
      "Enyan Abaasa New Town",
      "Enyan Abaasa Old Town",
      "Enyan Abaasa Zongo",
      "Enyan Denkyira",
      "Enyan Denkyira Junction",
      "Enyan Denkyira New Town",
      "Enyan Denkyira Old Town",
      "Enyan Denkyira Zongo",
      "Enyan Essiam",
      "Enyan Essiam Junction",
      "Enyan Essiam New Town",
      "Enyan Essiam Old Town",
      "Enyan Essiam Zongo",
      "Enyan Maim",
      "Enyan Maim Junction",
      "Enyan Maim New Town",
      "Enyan Maim Old Town",
      "Enyan Maim Zongo",
      "Essuekyir",
      "Essuekyir Junction",
      "Essuekyir New Town",
      "Essuekyir Old Town",
      "Essuekyir Zongo",
      "Asikuma",
      "Asikuma Junction",
      "Asikuma New Town",
      "Asikuma Old Town",
      "Asikuma Zongo",
      "Brakwa",
      "Brakwa Junction",
      "Brakwa New Town",
      "Brakwa Old Town",
      "Brakwa Zongo",
      "Breman Asikuma",
      "Breman Asikuma Junction",
      "Breman Asikuma New Town",
      "Breman Asikuma Old Town",
      "Breman Asikuma Zongo",
      "Odoben",
      "Odoben Junction",
      "Odoben New Town",
      "Odoben Old Town",
      "Odoben Zongo",
      "Assin Fosu",
      "Assin Fosu Junction",
      "Assin Fosu New Town",
      "Assin Fosu Old Town",
      "Assin Fosu Zongo",
      "Assin Akonfudi",
      "Assin Akonfudi Junction",
      "Assin Akonfudi New Town",
      "Assin Akonfudi Old Town",
      "Assin Akonfudi Zongo",
      "Assin Bereku",
      "Assin Bereku Junction",
      "Assin Bereku New Town",
      "Assin Bereku Old Town",
      "Assin Bereku Zongo",
      "Assin Manso",
      "Assin Manso Junction",
      "Assin Manso New Town",
      "Assin Manso Old Town",
      "Assin Manso Zongo",
      "Assin North",
      "Assin Akropong",
      "Assin Akropong Junction",
      "Assin Akropong New Town",
      "Assin Akropong Old Town",
      "Assin Akropong Zongo",
      "Assin Fosu",
      "Assin Praso",
      "Assin Praso Junction",
      "Assin Praso New Town",
      "Assin Praso Old Town",
      "Assin Praso Zongo",
      "Assin South",
      "Assin Adadientem",
      "Assin Adadientem Junction",
      "Assin Adadientem New Town",
      "Assin Adadientem Old Town",
      "Assin Adadientem Zongo",
      "Awutu",
      "Awutu Junction",
      "Awutu New Town",
      "Awutu Old Town",
      "Awutu Zongo",
      "Bawjiase",
      "Bawjiase Junction",
      "Bawjiase New Town",
      "Bawjiase Old Town",
      "Bawjiase Zongo",
      "Senya",
      "Senya Junction",
      "Senya New Town",
      "Senya Old Town",
      "Senya Zongo",
      "Senya Beraku",
      "Senya Beraku Junction",
      "Senya Beraku New Town",
      "Senya Beraku Old Town",
      "Senya Beraku Zongo",
      "Effutu Municipal",
      "Winneba",
      "Winneba Junction",
      "Winneba New Town",
      "Winneba Old Town",
      "Winneba Zongo",
      "Ateitu",
      "Ateitu Junction",
      "Ateitu New Town",
      "Ateitu Old Town",
      "Ateitu Zongo",
      "Kwashiebu",
      "Kwashiebu Junction",
      "Kwashiebu New Town",
      "Kwashiebu Old Town",
      "Kwashiebu Zongo",
      "Ekumfi Abor",
      "Ekumfi Abor Junction",
      "Ekumfi Abor New Town",
      "Ekumfi Abor Old Town",
      "Ekumfi Abor Zongo",
      "Ekumfi Aboano",
      "Ekumfi Aboano Junction",
      "Ekumfi Aboano New Town",
      "Ekumfi Aboano Old Town",
      "Ekumfi Aboano Zongo",
      "Ekumfi Essarkyir",
      "Ekumfi Essarkyir Junction",
      "Ekumfi Essarkyir New Town",
      "Ekumfi Essarkyir Old Town",
      "Ekumfi Essarkyir Zongo",
      "Ekumfi Otuam",
      "Ekumfi Otuam Junction",
      "Ekumfi Otuam New Town",
      "Ekumfi Otuam Old Town",
      "Ekumfi Otuam Zongo",
      "Gomoa Abonko",
      "Gomoa Abonko Junction",
      "Gomoa Abonko New Town",
      "Gomoa Abonko Old Town",
      "Gomoa Abonko Zongo",
      "Gomoa Fetteh",
      "Gomoa Fetteh Junction",
      "Gomoa Fetteh New Town",
      "Gomoa Fetteh Old Town",
      "Gomoa Fetteh Zongo",
      "Gomoa Ojobi",
      "Gomoa Ojobi Junction",
      "Gomoa Ojobi New Town",
      "Gomoa Ojobi Old Town",
      "Gomoa Ojobi Zongo",
      "Gomoa Pomadze",
      "Gomoa Pomadze Junction",
      "Gomoa Pomadze New Town",
      "Gomoa Pomadze Old Town",
      "Gomoa Pomadze Zongo",
      "Komenda",
      "Komenda Junction",
      "Komenda New Town",
      "Komenda Old Town",
      "Komenda Zongo",
      "Edina",
      "Edina Junction",
      "Edina New Town",
      "Edina Old Town",
      "Edina Zongo",
      "Eguafo",
      "Eguafo Junction",
      "Eguafo New Town",
      "Eguafo Old Town",
      "Eguafo Zongo",
      "Abirem",
      "Abirem Junction",
      "Abirem New Town",
      "Abirem Old Town",
      "Abirem Zongo",
      "Anomabo",
      "Anomabo Junction",
      "Anomabo New Town",
      "Anomabo Old Town",
      "Anomabo Zongo",
      "Biriwa",
      "Biriwa Junction",
      "Biriwa New Town",
      "Biriwa Old Town",
      "Biriwa Zongo",
      "Eguase",
      "Eguase Junction",
      "Eguase New Town",
      "Eguase Old Town",
      "Eguase Zongo",
      "Mankessim",
      "Mankessim Junction",
      "Mankessim New Town",
      "Mankessim Old Town",
      "Mankessim Zongo",
      "Saltpond",
      "Saltpond Junction",
      "Saltpond New Town",
      "Saltpond Old Town",
      "Saltpond Zongo",
      "Atti Morkwa",
      "Atti Morkwa Junction",
      "Atti Morkwa New Town",
      "Atti Morkwa Old Town",
      "Atti Morkwa Zongo",
      "Twifo Hemang",
      "Twifo Hemang Junction",
      "Twifo Hemang New Town",
      "Twifo Hemang Old Town",
      "Twifo Hemang Zongo",
      "Twifo Praso",
      "Twifo Praso Junction",
      "Twifo Praso New Town",
      "Twifo Praso Old Town",
      "Twifo Praso Zongo",
      "Dunkwa-on-Offin",
      "Dunkwa-on-Offin Junction",
      "Dunkwa-on-Offin New Town",
      "Dunkwa-on-Offin Old Town",
      "Dunkwa-on-Offin Zongo",
      "Aponapon",
      "Aponapon Junction",
      "Aponapon New Town",
      "Aponapon Old Town",
      "Aponapon Zongo",
      "Breman",
      "Breman Junction",
      "Breman New Town",
      "Breman Old Town",
      "Breman Zongo",
      "Diaso",
      "Diaso Junction",
      "Diaso New Town",
      "Diaso Old Town",
      "Diaso Zongo",
      "Aboabo",
      "Aboabo Junction",
      "Aboabo New Town",
      "Aboabo Old Town",
      "Aboabo Zongo",
      "Jukwa",
      "Jukwa Junction",
      "Jukwa New Town",
      "Jukwa Old Town",
      "Jukwa Zongo",
      "Yamfo",
      "Yamfo Junction",
      "Yamfo New Town",
      "Yamfo Old Town",
      "Yamfo Zongo",
    ],
  },
  Eastern: {
    region: "Eastern",
    cities: [
      "Koforidua",
      "Adweso",
      "Asokore",
      "Beti",
      "Chraa",
      "Effiduase",
      "Koforidua Zongo",
      "Maase",
      "Oda",
      "Otan",
      "Suhum",
      "Suhum Krampa",
      "Suhum Nsuta",
      "Suhum Odumase",
      "Suhum Ahenbronum",
      "Suhum Asamankama",
      "Suhum Nkwanta",
      "Suhum Nsawam",
      "Suhum Osenase",
      "Aboasa",
      "Aboabo",
      "Aboabo Junction",
      "Aboabo New Town",
      "Aboabo Old Town",
      "Aboabo Zongo",
      "Ahenbronum",
      "Akote",
      "Akote Junction",
      "Akote New Town",
      "Akote Old Town",
      "Akote Zongo",
      "Asamankama",
      "Asamankama Junction",
      "Asamankama New Town",
      "Asamankama Old Town",
      "Asamankama Zongo",
      "Krampa",
      "Nsawam",
      "Nsuta",
      "Odumase",
      "Osenase",
      "Osenase Junction",
      "Osenase New Town",
      "Osenase Old Town",
      "Osenase Zongo",
      "Nkwanta",
      "Nsawam",
      "Nsawam Adoagyiri",
      "Adoagyiri",
      "Adoagyiri Junction",
      "Adoagyiri New Town",
      "Adoagyiri Old Town",
      "Adoagyiri Zongo",
      "Nsawam",
      "Nsawam Junction",
      "Nsawam New Town",
      "Nsawam Old Town",
      "Nsawam Zongo",
      "Somanya",
      "Krobo Odumase",
      "Akuse",
      "Akuse Junction",
      "Akuse New Town",
      "Akuse Old Town",
      "Akuse Zongo",
      "Asesewa",
      "Asesewa Junction",
      "Asesewa New Town",
      "Asesewa Old Town",
      "Asesewa Zongo",
      "Kpong",
      "Kpong Junction",
      "Kpong New Town",
      "Kpong Old Town",
      "Kpong Zongo",
      "Kpongunor",
      "Kpongunor Junction",
      "Kpongunor New Town",
      "Kpongunor Old Town",
      "Kpongunor Zongo",
      "Odumase Krobo",
      "Agomanya",
      "Atimpoku",
      "Atimpoku Junction",
      "Atimpoku New Town",
      "Atimpoku Old Town",
      "Atimpoku Zongo",
      "Akim Oda",
      "Akim Oda Junction",
      "Akim Oda New Town",
      "Akim Oda Old Town",
      "Akim Oda Zongo",
      "Akyemansa",
      "Akyemansa Junction",
      "Akyemansa New Town",
      "Akyemansa Old Town",
      "Akyemansa Zongo",
      "Anum",
      "Anum Junction",
      "Anum New Town",
      "Anum Old Town",
      "Anum Zongo",
      "Anyinam",
      "Anyinam Junction",
      "Anyinam New Town",
      "Anyinam Old Town",
      "Anyinam Zongo",
      "Kibi",
      "Kibi Junction",
      "Kibi New Town",
      "Kibi Old Town",
      "Kibi Zongo",
      "Kwabeng",
      "Kwabeng Junction",
      "Kwabeng New Town",
      "Kwabeng Old Town",
      "Kwabeng Zongo",
      "Aduku",
      "Aduku Junction",
      "Aduku New Town",
      "Aduku Old Town",
      "Aduku Zongo",
      "Asamankese",
      "Asamankese Junction",
      "Asamankese New Town",
      "Asamankese Old Town",
      "Asamankese Zongo",
      "Akim Swedru",
      "Akim Swedru Junction",
      "Akim Swedru New Town",
      "Akim Swedru Old Town",
      "Akim Swedru Zongo",
      "Akyem Oda",
      "Akyem Oda Junction",
      "Akyem Oda New Town",
      "Akyem Oda Old Town",
      "Akyem Oda Zongo",
      "Akyem Swedru",
      "Akyem Swedru Junction",
      "Akyem Swedru New Town",
      "Akyem Swedru Old Town",
      "Akyem Swedru Zongo",
      "Akyem Tafo",
      "Akyem Tafo Junction",
      "Akyem Tafo New Town",
      "Akyem Tafo Old Town",
      "Akyem Tafo Zongo",
      "Abene",
      "Abene Junction",
      "Abene New Town",
      "Abene Old Town",
      "Abene Zongo",
      "Abetifi",
      "Abetifi Junction",
      "Abetifi New Town",
      "Abetifi Old Town",
      "Abetifi Zongo",
      "Pepease",
      "Pepease Junction",
      "Pepease New Town",
      "Pepease Old Town",
      "Pepease Zongo",
      "Mpraeso",
      "Mpraeso Junction",
      "Mpraeso New Town",
      "Mpraeso Old Town",
      "Mpraeso Zongo",
      "Nkwatia",
      "Nkwatia Junction",
      "Nkwatia New Town",
      "Nkwatia Old Town",
      "Nkwatia Zongo",
      "Nkawkaw",
      "Nkawkaw Junction",
      "Nkawkaw New Town",
      "Nkawkaw Old Town",
      "Nkawkaw Zongo",
      "Obo",
      "Obo Junction",
      "Obo New Town",
      "Obo Old Town",
      "Obo Zongo",
      "Begoro",
      "Begoro Junction",
      "Begoro New Town",
      "Begoro Old Town",
      "Begoro Zongo",
      "Osino",
      "Osino Junction",
      "Osino New Town",
      "Osino Old Town",
      "Osino Zongo",
      "Adukrom",
      "Adukrom Junction",
      "Adukrom New Town",
      "Adukrom Old Town",
      "Adukrom Zongo",
      "Akim Oda",
      "Larteh",
      "Larteh Junction",
      "Larteh New Town",
      "Larteh Old Town",
      "Larteh Zongo",
      "Aburi",
      "Aburi Junction",
      "Aburi New Town",
      "Aburi Old Town",
      "Aburi Zongo",
      "Ofoase",
      "Ofoase Junction",
      "Ofoase New Town",
      "Ofoase Old Town",
      "Ofoase Zongo",
      "Akroso",
      "Akroso Junction",
      "Akroso New Town",
      "Akroso Old Town",
      "Akroso Zongo",
      "Manso",
      "Manso Junction",
      "Manso New Town",
      "Manso Old Town",
      "Manso Zongo",
      "Kade",
      "Kade Junction",
      "Kade New Town",
      "Kade Old Town",
      "Kade Zongo",
      "Adeiso",
      "Adeiso Junction",
      "Adeiso New Town",
      "Adeiso Old Town",
      "Adeiso Zongo",
    ],
  },
  Volta: {
    region: "Volta",
    cities: [
      "Ho",
      "Ho Bankoe",
      "Ho Dome",
      "Ho Kpodzi",
      "Ho Zongo",
      "Ho Ahoe",
      "Ho Ahoe Junction",
      "Ho Ahoe New Town",
      "Ho Ahoe Old Town",
      "Ho Ahoe Zongo",
      "Ho Bankoe Junction",
      "Ho Bankoe New Town",
      "Ho Bankoe Old Town",
      "Ho Bankoe Zongo",
      "Ho Dome Junction",
      "Ho Dome New Town",
      "Ho Dome Old Town",
      "Ho Dome Zongo",
      "Ho Kpodzi Junction",
      "Ho Kpodzi New Town",
      "Ho Kpodzi Old Town",
      "Ho Kpodzi Zongo",
      "Abutia Kpota",
      "Abutia Kpota Junction",
      "Abutia Kpota New Town",
      "Abutia Kpota Old Town",
      "Abutia Kpota Zongo",
      "Abutia Kloe",
      "Abutia Kloe Junction",
      "Abutia Kloe New Town",
      "Abutia Kloe Old Town",
      "Abutia Kloe Zongo",
      "Abutia Teti",
      "Abutia Teti Junction",
      "Abutia Teti New Town",
      "Abutia Teti Old Town",
      "Abutia Teti Zongo",
      "Akatakyi",
      "Akatakyi Junction",
      "Akatakyi New Town",
      "Akatakyi Old Town",
      "Akatakyi Zongo",
      "Kpedze",
      "Kpedze Junction",
      "Kpedze New Town",
      "Kpedze Old Town",
      "Kpedze Zongo",
      "Adaklu Waya",
      "Adaklu Waya Junction",
      "Adaklu Waya New Town",
      "Adaklu Waya Old Town",
      "Adaklu Waya Zongo",
      "Adaklu Tsrefe",
      "Adaklu Tsrefe Junction",
      "Adaklu Tsrefe New Town",
      "Adaklu Tsrefe Old Town",
      "Adaklu Tsrefe Zongo",
      "Adaklu Abui",
      "Adaklu Abui Junction",
      "Adaklu Abui New Town",
      "Adaklu Abui Old Town",
      "Adaklu Abui Zongo",
      "Adaklu Anfoe",
      "Adaklu Anfoe Junction",
      "Adaklu Anfoe New Town",
      "Adaklu Anfoe Old Town",
      "Adaklu Anfoe Zongo",
      "Agotime Kpetoe",
      "Agotime Kpetoe Junction",
      "Agotime Kpetoe New Town",
      "Agotime Kpetoe Old Town",
      "Agotime Kpetoe Zongo",
      "Ziope",
      "Ziope Junction",
      "Ziope New Town",
      "Ziope Old Town",
      "Ziope Zongo",
      "Kpetoe",
      "Kpetoe Junction",
      "Kpetoe New Town",
      "Kpetoe Old Town",
      "Kpetoe Zongo",
      "Ve Golokwati",
      "Ve Golokwati Junction",
      "Ve Golokwati New Town",
      "Ve Golokwati Old Town",
      "Ve Golokwati Zongo",
      "Ve Deme",
      "Ve Deme Junction",
      "Ve Deme New Town",
      "Ve Deme Old Town",
      "Ve Deme Zongo",
      "Aflao",
      "Aflao Junction",
      "Aflao New Town",
      "Aflao Old Town",
      "Aflao Zongo",
      "Ave Dakpa",
      "Ave Dakpa Junction",
      "Ave Dakpa New Town",
      "Ave Dakpa Old Town",
      "Ave Dakpa Zongo",
      "Ave Havi",
      "Ave Havi Junction",
      "Ave Havi New Town",
      "Ave Havi Old Town",
      "Ave Havi Zongo",
      "Ave Kpedze",
      "Ave Kpedze Junction",
      "Ave Kpedze New Town",
      "Ave Kpedze Old Town",
      "Ave Kpedze Zongo",
      "Avenorpedo",
      "Avenorpedo Junction",
      "Avenorpedo New Town",
      "Avenorpedo Old Town",
      "Avenorpedo Zongo",
      "Avenui",
      "Avenui Junction",
      "Avenui New Town",
      "Avenui Old Town",
      "Avenui Zongo",
      "Avenorpeme",
      "Avenorpeme Junction",
      "Avenorpeme New Town",
      "Avenorpeme Old Town",
      "Avenorpeme Zongo",
      "Weta",
      "Weta Junction",
      "Weta New Town",
      "Weta Old Town",
      "Weta Zongo",
      "Tsiame",
      "Tsiame Junction",
      "Tsiame New Town",
      "Tsiame Old Town",
      "Tsiame Zongo",
      "Alakple",
      "Alakple Junction",
      "Alakple New Town",
      "Alakple Old Town",
      "Alakple Zongo",
      "Adidome",
      "Adidome Junction",
      "Adidome New Town",
      "Adidome Old Town",
      "Adidome Zongo",
      "Mezanokope",
      "Mezanokope Junction",
      "Mezanokope New Town",
      "Mezanokope Old Town",
      "Mezanokope Zongo",
      "Torgorme",
      "Torgorme Junction",
      "Torgorme New Town",
      "Torgorme Old Town",
      "Torgorme Zongo",
      "Denu",
      "Denu Junction",
      "Denu New Town",
      "Denu Old Town",
      "Denu Zongo",
      "Alavanyo",
      "Alavanyo Junction",
      "Alavanyo New Town",
      "Alavanyo Old Town",
      "Alavanyo Zongo",
      "Gbi Atabu",
      "Gbi Atabu Junction",
      "Gbi Atabu New Town",
      "Gbi Atabu Old Town",
      "Gbi Atabu Zongo",
      "Gbi Blaju",
      "Gbi Blaju Junction",
      "Gbi Blaju New Town",
      "Gbi Blaju Old Town",
      "Gbi Blaju Zongo",
      "Gbi Kledzo",
      "Gbi Kledzo Junction",
      "Gbi Kledzo New Town",
      "Gbi Kledzo Old Town",
      "Gbi Kledzo Zongo",
      "Keta",
      "Keta Junction",
      "Keta New Town",
      "Keta Old Town",
      "Keta Zongo",
      "Anyanui",
      "Anyanui Junction",
      "Anyanui New Town",
      "Anyanui Old Town",
      "Anyanui Zongo",
      "Kedzi",
      "Kedzi Junction",
      "Kedzi New Town",
      "Kedzi Old Town",
      "Kedzi Zongo",
      "Akanu",
      "Akanu Junction",
      "Akanu New Town",
      "Akanu Old Town",
      "Akanu Zongo",
      "Avetile",
      "Avetile Junction",
      "Avetile New Town",
      "Avetile Old Town",
      "Avetile Zongo",
      "Penyi",
      "Penyi Junction",
      "Penyi New Town",
      "Penyi Old Town",
      "Penyi Zongo",
      "Adafoe",
      "Adafoe Junction",
      "Adafoe New Town",
      "Adafoe Old Town",
      "Adafoe Zongo",
      "Kpandu Torkor",
      "Kpandu Torkor Junction",
      "Kpandu Torkor New Town",
      "Kpandu Torkor Old Town",
      "Kpandu Torkor Zongo",
      "Torkor",
      "Torkor Junction",
      "Torkor New Town",
      "Torkor Old Town",
      "Torkor Zongo",
      "Dambai",
      "Dambai Junction",
      "Dambai New Town",
      "Dambai Old Town",
      "Dambai Zongo",
      "Kete Krachi",
      "Kete Krachi Junction",
      "Kete Krachi New Town",
      "Kete Krachi Old Town",
      "Kete Krachi Zongo",
      "Chinderi",
      "Chinderi Junction",
      "Chinderi New Town",
      "Chinderi Old Town",
      "Chinderi Zongo",
      "Kpassa",
      "Kpassa Junction",
      "Kpassa New Town",
      "Kpassa Old Town",
      "Kpassa Zongo",
      "Nkwanta",
      "Nkwanta Junction",
      "Nkwanta New Town",
      "Nkwanta Old Town",
      "Nkwanta Zongo",
      "Anfoega",
      "Anfoega Junction",
      "Anfoega New Town",
      "Anfoega Old Town",
      "Anfoega Zongo",
      "Wusuta",
      "Wusuta Junction",
      "Wusuta New Town",
      "Wusuta Old Town",
      "Wusuta Zongo",
      "Battor",
      "Battor Junction",
      "Battor New Town",
      "Battor Old Town",
      "Battor Zongo",
      "Dabala",
      "Dabala Junction",
      "Dabala New Town",
      "Dabala Old Town",
      "Dabala Zongo",
      "Peki",
      "Peki Junction",
      "Peki New Town",
      "Peki Old Town",
      "Peki Zongo",
      "Tsito",
      "Tsito Junction",
      "Tsito New Town",
      "Tsito Old Town",
      "Tsito Zongo",
      "Sogakope",
      "Sogakope Junction",
      "Sogakope New Town",
      "Sogakope Old Town",
      "Sogakope Zongo",
      "Mepe",
      "Mepe Junction",
      "Mepe New Town",
      "Mepe Old Town",
      "Mepe Zongo",
      "Dzodze",
      "Dzodze Junction",
      "Dzodze New Town",
      "Dzodze Old Town",
      "Dzodze Zongo",
    ],
  },
  Northern: {
    region: "Northern",
    cities: [
      "Tamale",
      "Tamale Metro",
      "Tamale North",
      "Tamale South",
      "Abonsaw",
      "Aboabo",
      "Aboabo No. 1",
      "Aboabo No. 2",
      "Aboabo No. 3",
      "Aboabo No. 4",
      "Aboabo No. 5",
      "Aboabo No. 6",
      "Aboabo No. 7",
      "Aboabo No. 8",
      "Aboabo No. 9",
      "Aboabo Zongo",
      "Adaboya",
      "Adaboya Junction",
      "Adaboya New Town",
      "Adaboya Old Town",
      "Adaboya Zongo",
      "Choggu",
      "Choggu Yepalsi",
      "Choggu Zango",
      "Choggu Zongo",
      "Dungu",
      "Dungu Junction",
      "Dungu New Town",
      "Dungu Old Town",
      "Dungu Zongo",
      "Fufo",
      "Fufo Junction",
      "Fufo New Town",
      "Fufo Old Town",
      "Fufo Zongo",
      "Gbulung",
      "Gbulung Junction",
      "Gbulung New Town",
      "Gbulung Old Town",
      "Gbulung Zongo",
      "Gumani",
      "Gumani Junction",
      "Gumani New Town",
      "Gumani Old Town",
      "Gumani Zongo",
      "Jisonayili",
      "Jisonayili Junction",
      "Jisonayili New Town",
      "Jisonayili Old Town",
      "Jisonayili Zongo",
      "Kalpohin",
      "Kalpohin Estate",
      "Kalpohin Junction",
      "Kalpohin New Town",
      "Kalpohin Old Town",
      "Kalpohin Zongo",
      "Kambali",
      "Kambali Junction",
      "Kambali New Town",
      "Kambali Old Town",
      "Kambali Zongo",
      "Katariga",
      "Katariga Junction",
      "Katariga New Town",
      "Katariga Old Town",
      "Katariga Zongo",
      "Shishegu",
      "Shishegu Junction",
      "Shishegu New Town",
      "Shishegu Old Town",
      "Shishegu Zongo",
      "Tamale Central",
      "Tamale Estates",
      "Tamale Sagnarigu",
      "Tamale Vitting",
      "Tamale Zogbelgu",
      "Tamale Zongo",
      "Tishigu",
      "Tishigu Junction",
      "Tishigu New Town",
      "Tishigu Old Town",
      "Tishigu Zongo",
      "Vitting",
      "Vitting Junction",
      "Vitting New Town",
      "Vitting Old Town",
      "Vitting Zongo",
      "Wamale",
      "Wamale Junction",
      "Wamale New Town",
      "Wamale Old Town",
      "Wamale Zongo",
      "Zogbelgu",
      "Zogbelgu Junction",
      "Zogbelgu New Town",
      "Zogbelgu Old Town",
      "Zogbelgu Zongo",
      "Kpalsogu",
      "Kpalsogu Junction",
      "Kpalsogu New Town",
      "Kpalsogu Old Town",
      "Kpalsogu Zongo",
      "Kukobila",
      "Kukobila Junction",
      "Kukobila New Town",
      "Kukobila Old Town",
      "Kukobila Zongo",
      "Tampion",
      "Tampion Junction",
      "Tampion New Town",
      "Tampion Old Town",
      "Tampion Zongo",
      "Gushegu",
      "Gushegu Junction",
      "Gushegu New Town",
      "Gushegu Old Town",
      "Gushegu Zongo",
      "Kukpong",
      "Kukpong Junction",
      "Kukpong New Town",
      "Kukpong Old Town",
      "Kukpong Zongo",
      "Kpandoli",
      "Kpandoli Junction",
      "Kpandoli New Town",
      "Kpandoli Old Town",
      "Kpandoli Zongo",
      "Kpatinga",
      "Kpatinga Junction",
      "Kpatinga New Town",
      "Kpatinga Old Town",
      "Kpatinga Zongo",
      "Karaga",
      "Karaga Junction",
      "Karaga New Town",
      "Karaga Old Town",
      "Karaga Zongo",
      "Kpachilo",
      "Kpachilo Junction",
      "Kpachilo New Town",
      "Kpachilo Old Town",
      "Kpachilo Zongo",
      "Kpali",
      "Kpali Junction",
      "Kpali New Town",
      "Kpali Old Town",
      "Kpali Zongo",
      "Kpandai",
      "Kpandai Junction",
      "Kpandai New Town",
      "Kpandai Old Town",
      "Kpandai Zongo",
      "Chamba",
      "Chamba Junction",
      "Chamba New Town",
      "Chamba Old Town",
      "Chamba Zongo",
      "Kpandai Nakpali",
      "Kpandai Nakpali Junction",
      "Kpandai Nakpali New Town",
      "Kpandai Nakpali Old Town",
      "Kpandai Nakpali Zongo",
      "Kumbungu",
      "Kumbungu Junction",
      "Kumbungu New Town",
      "Kumbungu Old Town",
      "Kumbungu Zongo",
      "Dare",
      "Dare Junction",
      "Dare New Town",
      "Dare Old Town",
      "Dare Zongo",
      "Kpachaa",
      "Kpachaa Junction",
      "Kpachaa New Town",
      "Kpachaa Old Town",
      "Kpachaa Zongo",
      "Mion",
      "Mion Junction",
      "Mion New Town",
      "Mion Old Town",
      "Mion Zongo",
      "Bimbilla",
      "Bimbilla Junction",
      "Bimbilla New Town",
      "Bimbilla Old Town",
      "Bimbilla Zongo",
      "Nakpali",
      "Nakpali Junction",
      "Nakpali New Town",
      "Nakpali Old Town",
      "Nakpali Zongo",
      "Nalerigu",
      "Nalerigu Junction",
      "Nalerigu New Town",
      "Nalerigu Old Town",
      "Nalerigu Zongo",
      "Wulensi",
      "Wulensi Junction",
      "Wulensi New Town",
      "Wulensi Old Town",
      "Wulensi Zongo",
      "Nanton",
      "Nanton Junction",
      "Nanton New Town",
      "Nanton Old Town",
      "Nanton Zongo",
      "Saboba",
      "Saboba Junction",
      "Saboba New Town",
      "Saboba Old Town",
      "Saboba Zongo",
      "Chereponi",
      "Chereponi Junction",
      "Chereponi New Town",
      "Chereponi Old Town",
      "Chereponi Zongo",
      "Savelugu",
      "Savelugu Junction",
      "Savelugu New Town",
      "Savelugu Old Town",
      "Savelugu Zongo",
      "Diari",
      "Diari Junction",
      "Diari New Town",
      "Diari Old Town",
      "Diari Zongo",
      "Pong-Tamale",
      "Pong-Tamale Junction",
      "Pong-Tamale New Town",
      "Pong-Tamale Old Town",
      "Pong-Tamale Zongo",
      "Tatale",
      "Tatale Junction",
      "Tatale New Town",
      "Tatale Old Town",
      "Tatale Zongo",
      "Sanguli",
      "Sanguli Junction",
      "Sanguli New Town",
      "Sanguli Old Town",
      "Sanguli Zongo",
      "Tolon",
      "Tolon Junction",
      "Tolon New Town",
      "Tolon Old Town",
      "Tolon Zongo",
      "Yendi",
      "Yendi Junction",
      "Yendi New Town",
      "Yendi Old Town",
      "Yendi Zongo",
      "Daboya",
      "Daboya Junction",
      "Daboya New Town",
      "Daboya Old Town",
      "Daboya Zongo",
      "Zabzugu",
      "Zabzugu Junction",
      "Zabzugu New Town",
      "Zabzugu Old Town",
      "Zabzugu Zongo",
      "Salaga",
    ],
  },
  "Upper East": {
    region: "Upper East",
    cities: [
      "Bolgatanga",
      "Bolgatanga Zongo",
      "Sumbrungu",
      "Sumbrungu Junction",
      "Sumbrungu New Town",
      "Sumbrungu Old Town",
      "Sumbrungu Zongo",
      "Gbetuo",
      "Gbetuo Junction",
      "Gbetuo New Town",
      "Gbetuo Old Town",
      "Gbetuo Zongo",
      "Zuarungu",
      "Zuarungu Junction",
      "Zuarungu New Town",
      "Zuarungu Old Town",
      "Zuarungu Zongo",
      "Zea",
      "Zea Junction",
      "Zea New Town",
      "Zea Old Town",
      "Zea Zongo",
      "Yikene",
      "Yikene Junction",
      "Yikene New Town",
      "Yikene Old Town",
      "Yikene Zongo",
      "Gowrie",
      "Gowrie Junction",
      "Gowrie New Town",
      "Gowrie Old Town",
      "Gowrie Zongo",
      "Bawku",
      "Bawku Zongo",
      "Kpalwoga",
      "Kpalwoga Junction",
      "Kpalwoga New Town",
      "Kpalwoga Old Town",
      "Kpalwoga Zongo",
      "Kpalga",
      "Kpalga Junction",
      "Kpalga New Town",
      "Kpalga Old Town",
      "Kpalga Zongo",
      "Sagnarigu",
      "Sagnarigu Junction",
      "Sagnarigu New Town",
      "Sagnarigu Old Town",
      "Sagnarigu Zongo",
      "Zebilla",
      "Zebilla Junction",
      "Zebilla New Town",
      "Zebilla Old Town",
      "Zebilla Zongo",
      "Saga",
      "Saga Junction",
      "Saga New Town",
      "Saga Old Town",
      "Saga Zongo",
      "Kusasi",
      "Kusasi Junction",
      "Kusasi New Town",
      "Kusasi Old Town",
      "Kusasi Zongo",
      "Binduri",
      "Binduri Junction",
      "Binduri New Town",
      "Binduri Old Town",
      "Binduri Zongo",
      "Nangodi",
      "Nangodi Junction",
      "Nangodi New Town",
      "Nangodi Old Town",
      "Nangodi Zongo",
      "Bonia",
      "Bonia Junction",
      "Bonia New Town",
      "Bonia Old Town",
      "Bonia Zongo",
      "Sandema",
      "Sandema Junction",
      "Sandema New Town",
      "Sandema Old Town",
      "Sandema Zongo",
      "Chuchuliga",
      "Chuchuliga Junction",
      "Chuchuliga New Town",
      "Chuchuliga Old Town",
      "Chuchuliga Zongo",
      "Kanjaga",
      "Kanjaga Junction",
      "Kanjaga New Town",
      "Kanjaga Old Town",
      "Kanjaga Zongo",
      "Fumbisi",
      "Fumbisi Junction",
      "Fumbisi New Town",
      "Fumbisi Old Town",
      "Fumbisi Zongo",
      "Wiaga",
      "Wiaga Junction",
      "Wiaga New Town",
      "Wiaga Old Town",
      "Wiaga Zongo",
      "Siniensi",
      "Siniensi Junction",
      "Siniensi New Town",
      "Siniensi Old Town",
      "Siniensi Zongo",
      "Garu",
      "Garu Junction",
      "Garu New Town",
      "Garu Old Town",
      "Garu Zongo",
      "Tempane",
      "Tempane Junction",
      "Tempane New Town",
      "Tempane Old Town",
      "Tempane Zongo",
      "Navrongo",
      "Navrongo Junction",
      "Navrongo New Town",
      "Navrongo Old Town",
      "Navrongo Zongo",
      "Kologo",
      "Kologo Junction",
      "Kologo New Town",
      "Kologo Old Town",
      "Kologo Zongo",
      "Mirigu",
      "Mirigu Junction",
      "Mirigu New Town",
      "Mirigu Old Town",
      "Mirigu Zongo",
      "Paga",
      "Paga Junction",
      "Paga New Town",
      "Paga Old Town",
      "Paga Zongo",
      "Katiu",
      "Katiu Junction",
      "Katiu New Town",
      "Katiu Old Town",
      "Katiu Zongo",
      "Kayoro",
      "Kayoro Junction",
      "Kayoro New Town",
      "Kayoro Old Town",
      "Kayoro Zongo",
      "Pusiga",
      "Pusiga Junction",
      "Pusiga New Town",
      "Pusiga Old Town",
      "Pusiga Zongo",
      "Kanjaaga",
      "Kanjaaga Junction",
      "Kanjaaga New Town",
      "Kanjaaga Old Town",
      "Kanjaaga Zongo",
      "Tongo",
      "Tongo Junction",
      "Tongo New Town",
      "Tongo Old Town",
      "Tongo Zongo",
      "Sheini",
      "Sheini Junction",
      "Sheini New Town",
      "Sheini Old Town",
      "Sheini Zongo",
      "Golingo",
      "Golingo Junction",
      "Golingo New Town",
      "Golingo Old Town",
      "Golingo Zongo",
    ],
  },
  "Upper West": {
    region: "Upper West",
    cities: [
      "Wa",
      "Wa Zongo",
      "Dobile",
      "Dobile Junction",
      "Dobile New Town",
      "Dobile Old Town",
      "Dobile Zongo",
      "Bamboli",
      "Bamboli Junction",
      "Bamboli New Town",
      "Bamboli Old Town",
      "Bamboli Zongo",
      "Charikpong",
      "Charikpong Junction",
      "Charikpong New Town",
      "Charikpong Old Town",
      "Charikpong Zongo",
      "Dori",
      "Dori Junction",
      "Dori New Town",
      "Dori Old Town",
      "Dori Zongo",
      "Kperisi",
      "Kperisi Junction",
      "Kperisi New Town",
      "Kperisi Old Town",
      "Kperisi Zongo",
      "Sombo",
      "Sombo Junction",
      "Sombo New Town",
      "Sombo Old Town",
      "Sombo Zongo",
      "Bulenga",
      "Bulenga Junction",
      "Bulenga New Town",
      "Bulenga Old Town",
      "Bulenga Zongo",
      "Busa",
      "Busa Junction",
      "Busa New Town",
      "Busa Old Town",
      "Busa Zongo",
      "Funsi",
      "Funsi Junction",
      "Funsi New Town",
      "Funsi Old Town",
      "Funsi Zongo",
      "Gwollu",
      "Gwollu Junction",
      "Gwollu New Town",
      "Gwollu Old Town",
      "Gwollu Zongo",
      "Wechiau",
      "Wechiau Junction",
      "Wechiau New Town",
      "Wechiau Old Town",
      "Wechiau Zongo",
      "Dorimon",
      "Dorimon Junction",
      "Dorimon New Town",
      "Dorimon Old Town",
      "Dorimon Zongo",
      "Piina",
      "Piina Junction",
      "Piina New Town",
      "Piina Old Town",
      "Piina Zongo",
      "Jirapa",
      "Jirapa Junction",
      "Jirapa New Town",
      "Jirapa Old Town",
      "Jirapa Zongo",
      "Gou",
      "Gou Junction",
      "Gou New Town",
      "Gou Old Town",
      "Gou Zongo",
      "Ulo",
      "Ulo Junction",
      "Ulo New Town",
      "Ulo Old Town",
      "Ulo Zongo",
      "Kpongu",
      "Kpongu Junction",
      "Kpongu New Town",
      "Kpongu Old Town",
      "Kpongu Zongo",
      "Lawra",
      "Lawra Junction",
      "Lawra New Town",
      "Lawra Old Town",
      "Lawra Zongo",
      "Eremon",
      "Eremon Junction",
      "Eremon New Town",
      "Eremon Old Town",
      "Eremon Zongo",
      "Tangaze",
      "Tangaze Junction",
      "Tangaze New Town",
      "Tangaze Old Town",
      "Tangaze Zongo",
      "Kambali",
      "Kambali Junction",
      "Kambali New Town",
      "Kambali Old Town",
      "Kambali Zongo",
      "Nadowli",
      "Nadowli Junction",
      "Nadowli New Town",
      "Nadowli Old Town",
      "Nadowli Zongo",
      "Kaleo",
      "Kaleo Junction",
      "Kaleo New Town",
      "Kaleo Old Town",
      "Kaleo Zongo",
      "Daffiama",
      "Daffiama Junction",
      "Daffiama New Town",
      "Daffiama Old Town",
      "Daffiama Zongo",
      "Bussie",
      "Bussie Junction",
      "Bussie New Town",
      "Bussie Old Town",
      "Bussie Zongo",
      "Nandom",
      "Nandom Junction",
      "Nandom New Town",
      "Nandom Old Town",
      "Nandom Zongo",
      "Ko",
      "Ko Junction",
      "Ko New Town",
      "Ko Old Town",
      "Ko Zongo",
      "Nandua",
      "Nandua Junction",
      "Nandua New Town",
      "Nandua Old Town",
      "Nandua Zongo",
      "Nawieri",
      "Nawieri Junction",
      "Nawieri New Town",
      "Nawieri Old Town",
      "Nawieri Zongo",
      "Lambussie",
      "Lambussie Junction",
      "Lambussie New Town",
      "Lambussie Old Town",
      "Lambussie Zongo",
      "Karnwe",
      "Karnwe Junction",
      "Karnwe New Town",
      "Karnwe Old Town",
      "Karnwe Zongo",
      "Tumu",
      "Tumu Junction",
      "Tumu New Town",
      "Tumu Old Town",
      "Tumu Zongo",
      "Bamboi",
      "Bamboi Junction",
      "Bamboi New Town",
      "Bamboi Old Town",
      "Bamboi Zongo",
      "Bole",
      "Bole Junction",
      "Bole New Town",
      "Bole Old Town",
      "Bole Zongo",
      "Kulmasa",
      "Kulmasa Junction",
      "Kulmasa New Town",
      "Kulmasa Old Town",
      "Kulmasa Zongo",
      "Issa",
      "Issa Junction",
      "Issa New Town",
      "Issa Old Town",
      "Issa Zongo",
    ],
  },
  Bono: {
    region: "Bono",
    cities: [
      "Sunyani",
      "Sunyani Zongo",
      "Abesim",
      "Abesim Junction",
      "Abesim New Town",
      "Abesim Old Town",
      "Abesim Zongo",
      "Antwiadaka",
      "Antwiadaka Junction",
      "Antwiadaka New Town",
      "Antwiadaka Old Town",
      "Antwiadaka Zongo",
      "Fiawoyie",
      "Fiawoyie Junction",
      "Fiawoyie New Town",
      "Fiawoyie Old Town",
      "Fiawoyie Zongo",
      "New Dormaa",
      "New Dormaa Junction",
      "New Dormaa New Town",
      "New Dormaa Old Town",
      "New Dormaa Zongo",
      "Nsoatre",
      "Nsoatre Junction",
      "Nsoatre New Town",
      "Nsoatre Old Town",
      "Nsoatre Zongo",
      "Odumase",
      "Odumase Junction",
      "Odumase New Town",
      "Odumase Old Town",
      "Odumase Zongo",
      "Kwabre",
      "Kwabre Junction",
      "Kwabre New Town",
      "Kwabre Old Town",
      "Kwabre Zongo",
      "Chiraa",
      "Chiraa Junction",
      "Chiraa New Town",
      "Chiraa Old Town",
      "Chiraa Zongo",
      "Nkrankwanta",
      "Nkrankwanta Junction",
      "Nkrankwanta New Town",
      "Nkrankwanta Old Town",
      "Nkrankwanta Zongo",
      "Dormaa Ahenkro",
      "Dormaa Ahenkro Junction",
      "Dormaa Ahenkro New Town",
      "Dormaa Ahenkro Old Town",
      "Dormaa Ahenkro Zongo",
      "Wamfie",
      "Wamfie Junction",
      "Wamfie New Town",
      "Wamfie Old Town",
      "Wamfie Zongo",
      "Kyeremasu",
      "Kyeremasu Junction",
      "Kyeremasu New Town",
      "Kyeremasu Old Town",
      "Kyeremasu Zongo",
      "Kwakuom",
      "Kwakuom Junction",
      "Kwakuom New Town",
      "Kwakuom Old Town",
      "Kwakuom Zongo",
      "Berekum",
      "Berekum Zongo",
      "Biadan",
      "Biadan Junction",
      "Biadan New Town",
      "Biadan Old Town",
      "Biadan Zongo",
      "Kato",
      "Kato Junction",
      "Kato New Town",
      "Kato Old Town",
      "Kato Zongo",
      "Domfete",
      "Domfete Junction",
      "Domfete New Town",
      "Domfete Old Town",
      "Domfete Zongo",
      "Kwame Danso",
      "Kwame Danso Junction",
      "Kwame Danso New Town",
      "Kwame Danso Old Town",
      "Kwame Danso Zongo",
      "Senase",
      "Senase Junction",
      "Senase New Town",
      "Senase Old Town",
      "Senase Zongo",
      "Sampa",
      "Sampa Junction",
      "Sampa New Town",
      "Sampa Old Town",
      "Sampa Zongo",
      "Drobo",
      "Drobo Junction",
      "Drobo New Town",
      "Drobo Old Town",
      "Drobo Zongo",
      "Japekrom",
      "Japekrom Junction",
      "Japekrom New Town",
      "Japekrom Old Town",
      "Japekrom Zongo",
      "Bechem",
      "Bechem Junction",
      "Bechem New Town",
      "Bechem Old Town",
      "Bechem Zongo",
      "Atronie",
      "Atronie Junction",
      "Atronie New Town",
      "Atronie Old Town",
      "Atronie Zongo",
      "Nchiraa",
      "Nchiraa Junction",
      "Nchiraa New Town",
      "Nchiraa Old Town",
      "Nchiraa Zongo",
      "Seikwa",
      "Seikwa Junction",
      "Seikwa New Town",
      "Seikwa Old Town",
      "Seikwa Zongo",
      "Brodi",
      "Brodi Junction",
      "Brodi New Town",
      "Brodi Old Town",
      "Brodi Zongo",
      "Wenchi",
      "Wenchi Zongo",
      "Subinso No. 1",
      "Subinso No. 1 Junction",
      "Subinso No. 1 New Town",
      "Subinso No. 1 Old Town",
      "Subinso No. 1 Zongo",
      "Subinso No. 2",
      "Subinso No. 2 Junction",
      "Subinso No. 2 New Town",
      "Subinso No. 2 Old Town",
      "Subinso No. 2 Zongo",
      "Banda Ahenkro",
      "Banda Ahenkro Junction",
      "Banda Ahenkro New Town",
      "Banda Ahenkro Old Town",
      "Banda Ahenkro Zongo",
      "Banda Nkwanta",
      "Banda Nkwanta Junction",
      "Banda Nkwanta New Town",
      "Banda Nkwanta Old Town",
      "Banda Nkwanta Zongo",
    ],
  },
  "Bono East": {
    region: "Bono East",
    cities: [
      "Techiman",
      "Techiman Zongo",
      "Tanoboase",
      "Tanoboase Junction",
      "Tanoboase New Town",
      "Tanoboase Old Town",
      "Tanoboase Zongo",
      "Nkwaeso",
      "Nkwaeso Junction",
      "Nkwaeso New Town",
      "Nkwaeso Old Town",
      "Nkwaeso Zongo",
      "Anyimasu",
      "Anyimasu Junction",
      "Anyimasu New Town",
      "Anyimasu Old Town",
      "Anyimasu Zongo",
      "Tuobodom",
      "Tuobodom Junction",
      "Tuobodom New Town",
      "Tuobodom Old Town",
      "Tuobodom Zongo",
      "Akrofrom",
      "Akrofrom Junction",
      "Akrofrom New Town",
      "Akrofrom Old Town",
      "Akrofrom Zongo",
      "Brewaniase",
      "Brewaniase Junction",
      "Brewaniase New Town",
      "Brewaniase Old Town",
      "Brewaniase Zongo",
      "Akomfo",
      "Akomfo Junction",
      "Akomfo New Town",
      "Akomfo Old Town",
      "Akomfo Zongo",
      "Kintampo",
      "Kintampo Junction",
      "Kintampo New Town",
      "Kintampo Old Town",
      "Kintampo Zongo",
      "Jema",
      "Jema Junction",
      "Jema New Town",
      "Jema Old Town",
      "Jema Zongo",
      "Kadelso",
      "Kadelso Junction",
      "Kadelso New Town",
      "Kadelso Old Town",
      "Kadelso Zongo",
      "New Longoro",
      "New Longoro Junction",
      "New Longoro New Town",
      "New Longoro Old Town",
      "New Longoro Zongo",
      "Anyima",
      "Anyima Junction",
      "Anyima New Town",
      "Anyima Old Town",
      "Anyima Zongo",
      "Busunya",
      "Busunya Junction",
      "Busunya New Town",
      "Busunya Old Town",
      "Busunya Zongo",
      "Fiapre",
      "Fiapre Junction",
      "Fiapre New Town",
      "Fiapre Old Town",
      "Fiapre Zongo",
      "Ahenkro",
      "Ahenkro Junction",
      "Ahenkro New Town",
      "Ahenkro Old Town",
      "Ahenkro Zongo",
      "Nkoranza",
      "Nkoranza Junction",
      "Nkoranza New Town",
      "Nkoranza Old Town",
      "Nkoranza Zongo",
      "Atebubu",
      "Atebubu Junction",
      "Atebubu New Town",
      "Atebubu Old Town",
      "Atebubu Zongo",
      "Amantin",
      "Amantin Junction",
      "Amantin New Town",
      "Amantin Old Town",
      "Amantin Zongo",
      "Akomadan",
      "Akomadan Junction",
      "Akomadan New Town",
      "Akomadan Old Town",
      "Akomadan Zongo",
      "Yeji",
      "Yeji Junction",
      "Yeji New Town",
      "Yeji Old Town",
      "Yeji Zongo",
      "Ahamansu",
      "Ahamansu Junction",
      "Ahamansu New Town",
      "Ahamansu Old Town",
      "Ahamansu Zongo",
      "Aprade",
      "Aprade Junction",
      "Aprade New Town",
      "Aprade Old Town",
      "Aprade Zongo",
      "Prang",
      "Prang Junction",
      "Prang New Town",
      "Prang Old Town",
      "Prang Zongo",
      "Kwajaku",
      "Kwajaku Junction",
      "Kwajaku New Town",
      "Kwajaku Old Town",
      "Kwajaku Zongo",
    ],
  },
  "North East": {
    region: "North East",
    cities: [
      "Bunkpurugu",
      "Nakpanduri",
      "Gambaga",
      "Nalerigu",
      "Walewale",
      "Yagaba",
      "Saboba",
      "Langbinsi",
      "Yunyoo",
      "Nasuan",
      "Chereponi",
      "East Mamprusi",
      "Mamprugu Moagduri",
      "West Mamprusi",
    ],
  },
  Oti: {
    region: "Oti",
    cities: [
      "Dambai",
      "Jasikan",
      "Kadjebi",
      "Kadjebi-Asato",
      "Kete Krachi",
      "Krachi Nchumuru",
      "Nkwanta North",
      "Nkwanta South",
      "Brewaniase",
      "Kpassa",
      "Kwame Danso",
      "Yabram",
      "Kadjei",
      "Chinderi",
      "Kwame Ameyaw",
      "Nkonya",
      "Banda Ahenkro",
    ],
  },
  Savanna: {
    region: "Savanna",
    cities: [
      "Damongo",
      "Buipe",
      "Bole",
      "Bamboi",
      "Mankuma",
      "Larabanga",
      "Busunu",
      "Fulaso",
      "Kpalbe",
      "Kpembe",
      "Salaga",
      "Tuna",
      "Kalba",
      "Daboya",
      "Fufulso",
      "Central Gonja",
      "East Gonja",
      "North Gonja",
      "Sawla",
      "Sawla-Tuna-Kalba",
      "West Gonja",
    ],
  },
}

export const getAllGhanaLocations = (): string[] => {
  const locations = new Set<string>()
  Object.values(GHANA_LOCATIONS).forEach((region) => {
    region.cities.forEach((city) => {
      locations.add(city)
    })
    locations.add(region.region)
  })
  return Array.from(locations).sort()
}

export const isLocationInGhana = (location: string): boolean => {
  const allLocations = getAllGhanaLocations()
  return allLocations.some((loc) => loc.toLowerCase() === location.toLowerCase())
}

export const getNearbyLocations = (location: string): string[] => {
  const normalizedLocation = location.toLowerCase()
  for (const region of Object.values(GHANA_LOCATIONS)) {
    if (region.region.toLowerCase() === normalizedLocation) {
      return region.cities
    }
    if (region.cities.some((city) => city.toLowerCase() === normalizedLocation)) {
      return region.cities.filter((city) => city.toLowerCase() !== normalizedLocation)
    }
  }
  return []
}
